In [1]:
# Resources
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df_2020 = pd.read_csv('Resources/FF_Stats_2020.csv')
df_2020.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0

In [4]:
df_2020["Year"] = '2020'
df_2020.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Derrick Henry,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0,2020
1,2,Alvin Kamara,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0,2020
2,3,Dalvin Cook,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0,2020
3,4,Davante Adams,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0,2020
4,5,Travis Kelce,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0,2020

In [5]:
df_2020.columns

Index(['Rk', 'Player', 'Tm', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att.1', 'Yds.1', 'Y/A', 'TD.1', 'Tgt', 'Rec', 'Yds.2',
       'Y/R', 'TD.2', 'Fmb', 'FL', 'TD.3', '2PM', '2PP', 'FantPt', 'PPR',
       'DKPt', 'FDPt', 'VBD', 'PosRank', 'OvRank', 'Year'],
      dtype='object')

In [6]:
df_2020 = df_2020[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att.1', 'Yds.1', 'Y/A', 'TD.1', 'Tgt', 'Rec', 'Yds.2',
       'Y/R', 'TD.2', 'Fmb', 'FL', 'TD.3', '2PM', '2PP', 'FantPt', 'PPR',
       'DKPt', 'FDPt', 'VBD', 'PosRank', 'OvRank']]
df_2020.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce,KAN,2020,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0

In [7]:
df_2019 = pd.read_csv('Resources/FF_Stats_2019.csv')
df_2019.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey,CAR,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,NaN,355.0,471.2,477.2,413.2,215.0,1,1.0
1,2,Lamar Jackson,BAL,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9,2,7,NaN,NaN,416.0,415.7,429.7,421.7,152.0,1,2.0
2,3,Derrick Henry,TEN,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,NaN,NaN,277.0,294.6,303.6,285.6,136.0,2,3.0
3,4,Aaron Jones,GNB,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3,2,19,NaN,NaN,266.0,314.8,322.8,290.3,125.0,3,4.0
4,5,Ezekiel Elliott,DAL,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3,2,14,NaN,NaN,258.0,311.7,319.7,284.7,117.0,4,5.0

In [8]:
df_2019["Year"] = '2019'
df_2019.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Christian McCaffrey,CAR,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,NaN,355.0,471.2,477.2,413.2,215.0,1,1.0,2019
1,2,Lamar Jackson,BAL,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9,2,7,NaN,NaN,416.0,415.7,429.7,421.7,152.0,1,2.0,2019
2,3,Derrick Henry,TEN,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,NaN,NaN,277.0,294.6,303.6,285.6,136.0,2,3.0,2019
3,4,Aaron Jones,GNB,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3,2,19,NaN,NaN,266.0,314.8,322.8,290.3,125.0,3,4.0,2019
4,5,Ezekiel Elliott,DAL,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3,2,14,NaN,NaN,258.0,311.7,319.7,284.7,117.0,4,5.0,2019

In [9]:
df_2019 = df_2019[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att.1', 'Yds.1', 'Y/A', 'TD.1', 'Tgt', 'Rec', 'Yds.2',
       'Y/R', 'TD.2', 'Fmb', 'FL', 'TD.3', '2PM', '2PP', 'FantPt', 'PPR',
       'DKPt', 'FDPt', 'VBD', 'PosRank', 'OvRank']]
df_2019.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,NaN,355.0,471.2,477.2,413.2,215.0,1,1.0
1,2,Lamar Jackson,BAL,2019,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9,2,7,NaN,NaN,416.0,415.7,429.7,421.7,152.0,1,2.0
2,3,Derrick Henry,TEN,2019,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,NaN,NaN,277.0,294.6,303.6,285.6,136.0,2,3.0
3,4,Aaron Jones,GNB,2019,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3,2,19,NaN,NaN,266.0,314.8,322.8,290.3,125.0,3,4.0
4,5,Ezekiel Elliott,DAL,2019,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3,2,14,NaN,NaN,258.0,311.7,319.7,284.7,117.0,4,5.0

In [10]:
df_2018 = pd.read_csv('Resources/FF_Stats_2018.csv')
df_2018.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Todd Gurley,LAR,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,NaN,313.0,372.1,379.1,342.6,178.0,1,1.0
1,2,Saquon Barkley,NYG,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,NaN,295.0,385.8,391.8,340.3,159.0,2,2.0
2,3,Christian McCaffrey,CAR,RB,22,16,16,1,1,50,1,0,219,1098,5.01,7,124,107,867,8.10,6,4,1,13,NaN,NaN,279.0,385.5,392.5,332.0,143.0,3,3.0
3,4,Alvin Kamara,NOR,RB,23,15,13,0,0,0,0,0,194,883,4.55,14,105,81,709,8.75,4,1,0,18,3.0,NaN,273.0,354.2,360.2,313.7,138.0,4,4.0
4,5,Patrick Mahomes,KAN,QB,23,16,16,383,580,5097,50,12,60,272,4.53,2,0,0,0,NaN,0,9,2,2,1.0,NaN,417.0,417.1,437.1,429.1,134.0,1,5.0

In [11]:
df_2018["Year"] = '2018'
df_2018.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Todd Gurley,LAR,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,NaN,313.0,372.1,379.1,342.6,178.0,1,1.0,2018
1,2,Saquon Barkley,NYG,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,NaN,295.0,385.8,391.8,340.3,159.0,2,2.0,2018
2,3,Christian McCaffrey,CAR,RB,22,16,16,1,1,50,1,0,219,1098,5.01,7,124,107,867,8.10,6,4,1,13,NaN,NaN,279.0,385.5,392.5,332.0,143.0,3,3.0,2018
3,4,Alvin Kamara,NOR,RB,23,15,13,0,0,0,0,0,194,883,4.55,14,105,81,709,8.75,4,1,0,18,3.0,NaN,273.0,354.2,360.2,313.7,138.0,4,4.0,2018
4,5,Patrick Mahomes,KAN,QB,23,16,16,383,580,5097,50,12,60,272,4.53,2,0,0,0,NaN,0,9,2,2,1.0,NaN,417.0,417.1,437.1,429.1,134.0,1,5.0,2018

In [12]:
df_2018 = df_2018[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att.1', 'Yds.1', 'Y/A', 'TD.1', 'Tgt', 'Rec', 'Yds.2',
       'Y/R', 'TD.2', 'Fmb', 'FL', 'TD.3', '2PM', '2PP', 'FantPt', 'PPR',
       'DKPt', 'FDPt', 'VBD', 'PosRank', 'OvRank']]
df_2018.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,NaN,313.0,372.1,379.1,342.6,178.0,1,1.0
1,2,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,NaN,295.0,385.8,391.8,340.3,159.0,2,2.0
2,3,Christian McCaffrey,CAR,2018,RB,22,16,16,1,1,50,1,0,219,1098,5.01,7,124,107,867,8.10,6,4,1,13,NaN,NaN,279.0,385.5,392.5,332.0,143.0,3,3.0
3,4,Alvin Kamara,NOR,2018,RB,23,15,13,0,0,0,0,0,194,883,4.55,14,105,81,709,8.75,4,1,0,18,3.0,NaN,273.0,354.2,360.2,313.7,138.0,4,4.0
4,5,Patrick Mahomes,KAN,2018,QB,23,16,16,383,580,5097,50,12,60,272,4.53,2,0,0,0,NaN,0,9,2,2,1.0,NaN,417.0,417.1,437.1,429.1,134.0,1,5.0

In [13]:
df_2020.columns

Index(['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att',
       'Yds', 'TD', 'Int', 'Att.1', 'Yds.1', 'Y/A', 'TD.1', 'Tgt', 'Rec',
       'Yds.2', 'Y/R', 'TD.2', 'Fmb', 'FL', 'TD.3', '2PM', '2PP', 'FantPt',
       'PPR', 'DKPt', 'FDPt', 'VBD', 'PosRank', 'OvRank'],
      dtype='object')

In [14]:
df_2020.dtypes

Rk           int64
Player      object
Tm          object
Year        object
FantPos     object
Age          int64
G            int64
GS           int64
Cmp          int64
Att          int64
Yds          int64
TD           int64
Int          int64
Att.1        int64
Yds.1        int64
Y/A        float64
TD.1         int64
Tgt          int64
Rec          int64
Yds.2        int64
Y/R        float64
TD.2         int64
Fmb          int64
FL           int64
TD.3         int64
2PM        float64
2PP        float64
FantPt     float64
PPR        float64
DKPt       float64
FDPt       float64
VBD        float64
PosRank      int64
OvRank     float64
dtype: object

In [15]:
all_df = [df_2020,df_2019,df_2018]
merge_df = pd.concat(all_df)
merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce,KAN,2020,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0

In [16]:
merge_df.count()

Rk         1853
Player     1853
Tm         1853
Year       1853
FantPos    1678
Age        1853
G          1853
GS         1853
Cmp        1853
Att        1853
Yds        1853
TD         1853
Int        1853
Att.1      1853
Yds.1      1853
Y/A         999
TD.1       1853
Tgt        1853
Rec        1853
Yds.2      1853
Y/R        1440
TD.2       1853
Fmb        1853
FL         1853
TD.3       1853
2PM         159
2PP          80
FantPt     1649
PPR        1681
DKPt       1681
FDPt       1682
VBD         219
PosRank    1853
OvRank      234
dtype: int64

In [17]:
new_merge_df = merge_df.fillna(0)
new_merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,0.0,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,0.0,0.0,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3.0,0.0,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,0,0,0.00,0,149,115,1374,11.95,18,1,1,18,0.0,0.0,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce,KAN,2020,TE,31,15,15,1,2,4,0,0,0,0,0.00,0,145,105,1416,13.49,11,1,1,11,1.0,0.0,208.0,312.8,316.8,260.3,117.0,1,5.0

In [18]:
new_merge_df=new_merge_df.sort_index(ascending=True)
new_merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,0.0,314.0,333.1,341.1,323.6,184.0,1,1.0
0,1,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,0.0,313.0,372.1,379.1,342.6,178.0,1,1.0
0,1,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,0.0,355.0,471.2,477.2,413.2,215.0,1,1.0
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,0.0,0.0,295.0,377.8,383.8,336.3,165.0,2,2.0
1,2,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,0.0,295.0,385.8,391.8,340.3,159.0,2,2.0

In [19]:
new_merge_df = new_merge_df.drop(columns='Rk')
new_merge_df.head()

,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,0.0,314.0,333.1,341.1,323.6,184.0,1,1.0
0,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,0.0,313.0,372.1,379.1,342.6,178.0,1,1.0
0,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,0.0,355.0,471.2,477.2,413.2,215.0,1,1.0
1,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,0.0,0.0,295.0,377.8,383.8,336.3,165.0,2,2.0
1,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,0.0,295.0,385.8,391.8,340.3,159.0,2,2.0

In [20]:
new_merge_df.Player = new_merge_df.Player.str.rstrip()

In [21]:
new_merge_df.reset_index(drop=True)

,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,0.0,314.0,333.1,341.1,323.6,184.0,1,1.0
1,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,0.0,313.0,372.1,379.1,342.6,178.0,1,1.0
2,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1.0,0.0,355.0,471.2,477.2,413.2,215.0,1,1.0
3,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,0.0,0.0,295.0,377.8,383.8,336.3,165.0,2,2.0
4,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1.0,0.0,295.0,385.8,391.8,340.3,159.0,2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1848,Andre Roberts,BUF,2020,WR,32,15,0,0,0,0,0,0,1,-3,-3.00,0,5,4,34,8.50,0,3,2,0,0.0,0.0,-1.0,3.1,5.1,1.1,0.0,243,0.0
1849,Nate Sudfeld,PHI,2020,QB,27,1,0,5,12,32,0,1,2,12,6.00,0,0,0,0,0.00,0,1,1,0,0.0,0.0,-2.0,-1.5,0.5,-0.5,0.0,83,0.0
1850,Nsimba Webster,LAR,2020,0,24,16,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.00,0,3,1,0,0.0,0.0,-2.0,-2.0,-1.0,-2.0,0.0,246,0.0
1851,Dede Westbrook,JAX,2020,WR,27,2,0,0,0,0,0,0,0,0,0.00,0,1,1,4,4.00,0,1,1,0,0.0,0.0,-2.0,-0.6,0.4,-1.1,0.0,245,0.0
1852,Kendall Hinton,DEN,2020,WR,23,1,0,1,9,13,0,2,2,7,3.50,0,0,0,0,0.00,0,0,0,0,0.0,0.0,-3.0,-2.8,-0.8,-0.8,0.0,247,0.0

In [27]:
#Copy and paste player name from any of the Stat files from the Resources folder
x = input("Enter Player Name:")

Enter Player Name:Todd Gurley

In [28]:
#Copy and paste player name from any of the Stat files from the Resources folder
y = input("Enter Player Name:")

Enter Player Name:Derrick Henry

In [29]:
player_input_1 = new_merge_df.loc[new_merge_df.loc[:,"Player"] == x, :].sort_values(by=['Year'])
player_input_1

,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,0.0,313.0,372.1,379.1,342.6,178.0,1,1.0
23,Todd Gurley,LAR,2019,RB,25,15,15,0,0,0,0,0,223,857,3.84,12,49,31,207,6.68,2,3,2,14,1.0,0.0,188.0,219.4,227.4,203.9,48.0,12,24.0
67,Todd Gurley,ATL,2020,RB,26,15,15,0,0,0,0,0,195,678,3.48,9,35,25,164,6.56,0,2,0,9,0.0,0.0,138.0,163.2,169.2,150.7,8.0,23,68.0

In [30]:
player_input_2 = new_merge_df.loc[new_merge_df.loc[:,"Player"] == y, :].sort_values(by=['Year'])
player_input_2

,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
29,Derrick Henry,TEN,2018,RB,24,16,12,2,3,14,0,0,215,1059,4.93,12,18,15,99,6.60,0,1,1,12,0.0,0.0,186.0,201.4,205.4,193.9,51.0,13,30.0
2,Derrick Henry,TEN,2019,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,0.0,0.0,277.0,294.6,303.6,285.6,136.0,2,3.0
0,Derrick Henry,TEN,2020,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1.0,0.0,314.0,333.1,341.1,323.6,184.0,1,1.0

In [31]:
players=[player_input_1, player_input_2]
player_merge = pd.concat(players)
player_merge.head()

,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,Todd Gurley,LAR,2018,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3.0,0.0,313.0,372.1,379.1,342.6,178.0,1,1.0
23,Todd Gurley,LAR,2019,RB,25,15,15,0,0,0,0,0,223,857,3.84,12,49,31,207,6.68,2,3,2,14,1.0,0.0,188.0,219.4,227.4,203.9,48.0,12,24.0
67,Todd Gurley,ATL,2020,RB,26,15,15,0,0,0,0,0,195,678,3.48,9,35,25,164,6.56,0,2,0,9,0.0,0.0,138.0,163.2,169.2,150.7,8.0,23,68.0
29,Derrick Henry,TEN,2018,RB,24,16,12,2,3,14,0,0,215,1059,4.93,12,18,15,99,6.60,0,1,1,12,0.0,0.0,186.0,201.4,205.4,193.9,51.0,13,30.0
2,Derrick Henry,TEN,2019,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,0.0,0.0,277.0,294.6,303.6,285.6,136.0,2,3.0