In [1]:
# Resources
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
#df_2020 = pd.read_csv('Resources/FF_Stats_2020.csv')
#df_2020.head()
URL = "https://www.pro-football-reference.com/years/2020/fantasy.htm"
df_2020 = pd.read_html(URL, match = 'Fantasy Rankings')

In [4]:
#converting table into pandas dataframe and droping extra header column
df_2020[0]
df_2020_data = pd.DataFrame(data=df_2020[0])
df_2020_data.columns = df_2020_data.columns.droplevel(0)
df_2020_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry *+,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1,NaN,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara *,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook*,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3,NaN,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce*+,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1,NaN,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams*+,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5

In [5]:
df_2020_data["Year"] = '2020'
df_2020_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Derrick Henry *+,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1,NaN,314,333.1,341.1,323.6,184,1,1,2020
1,2,Alvin Kamara *,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2,2020
2,3,Dalvin Cook*,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3,NaN,294,337.8,346.8,315.8,164,3,3,2020
3,4,Travis Kelce*+,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1,NaN,208,312.8,316.8,260.3,117,1,4,2020
4,5,Davante Adams*+,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5,2020

In [6]:
df_2020_data.columns

Index(['Rk', 'Player', 'Tm', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'Y/A', 'TD', 'Tgt', 'Rec', 'Yds', 'Y/R',
       'TD', 'Fmb', 'FL', 'TD', '2PM', '2PP', 'FantPt', 'PPR', 'DKPt', 'FDPt',
       'VBD', 'PosRank', 'OvRank', 'Year'],
      dtype='object')

In [7]:
df_2020_data = df_2020_data[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'Y/A', 'TD', 'Tgt', 'Rec', 'Yds', 'Y/R',
       'TD', 'Fmb', 'FL', 'TD', '2PM', '2PP', 'FantPt', 'PPR', 'DKPt', 'FDPt',
       'VBD', 'PosRank', 'OvRank']]
df_2020_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry *+,TEN,2020,RB,26,16,16,0,0,378,0,2027,114,0,17,0,17,0,0,378,0,2027,114,5.36,0,17,0,17,31,19,0,2027,114,6.00,0,17,0,17,3,2,0,17,0,17,1,NaN,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara *,NOR,2020,RB,25,15,10,0,0,187,0,932,756,0,16,5,21,0,0,187,0,932,756,4.98,0,16,5,21,107,83,0,932,756,9.11,0,16,5,21,1,0,0,16,5,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook*,MIN,2020,RB,25,14,14,0,0,312,0,1557,361,0,16,1,17,0,0,312,0,1557,361,4.99,0,16,1,17,54,44,0,1557,361,8.20,0,16,1,17,5,3,0,16,1,17,3,NaN,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce*+,KAN,2020,TE,31,15,15,1,2,0,4,0,1416,0,0,11,11,0,2,0,4,0,1416,NaN,0,0,11,11,145,105,4,0,1416,13.49,0,0,11,11,1,1,0,0,11,11,1,NaN,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams*+,GNB,2020,WR,28,14,14,0,0,0,0,0,1374,0,0,18,18,0,0,0,0,0,1374,NaN,0,0,18,18,149,115,0,0,1374,11.95,0,0,18,18,1,1,0,0,18,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5

In [8]:
spec_chars = ["!",'"',"#","%","&","'","(",")",
              "*","+",",","-",".","/",":",";","<",
              "=",">","?","@","[","\\","]","^","_",
              "`","{","|","}","~","–"]
for char in spec_chars:
    df_2020_data['Player'] = df_2020_data['Player'].str.replace(char, ' ')

In [9]:
df_2020_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,378,0,2027,114,0,17,0,17,0,0,378,0,2027,114,5.36,0,17,0,17,31,19,0,2027,114,6.00,0,17,0,17,3,2,0,17,0,17,1,NaN,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,187,0,932,756,0,16,5,21,0,0,187,0,932,756,4.98,0,16,5,21,107,83,0,932,756,9.11,0,16,5,21,1,0,0,16,5,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,312,0,1557,361,0,16,1,17,0,0,312,0,1557,361,4.99,0,16,1,17,54,44,0,1557,361,8.20,0,16,1,17,5,3,0,16,1,17,3,NaN,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce,KAN,2020,TE,31,15,15,1,2,0,4,0,1416,0,0,11,11,0,2,0,4,0,1416,NaN,0,0,11,11,145,105,4,0,1416,13.49,0,0,11,11,1,1,0,0,11,11,1,NaN,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,1374,0,0,18,18,0,0,0,0,0,1374,NaN,0,0,18,18,149,115,0,0,1374,11.95,0,0,18,18,1,1,0,0,18,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5

In [10]:
#df_2019 = pd.read_csv('Resources/FF_Stats_2019.csv')
#df_2019.head()
URL = "https://www.pro-football-reference.com/years/2019/fantasy.htm"
df_2019 = pd.read_html(URL, match = 'Fantasy Rankings')

In [11]:
#converting table into pandas dataframe and droping extra header column
df_2019[0]
df_2019_data = pd.DataFrame(data=df_2019[0])
df_2019_data.columns = df_2019_data.columns.droplevel(0)
df_2019_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey*+,CAR,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1,NaN,355,471.2,477.2,413.2,215,1,1
1,2,Lamar Jackson*+,BAL,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9,2,7,NaN,NaN,416,415.7,429.7,421.7,152,1,2
2,3,Derrick Henry *,TEN,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,NaN,NaN,277,294.6,303.6,285.6,136,2,3
3,4,Aaron Jones,GNB,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3,2,19,NaN,NaN,266,314.8,322.8,290.3,125,3,4
4,5,Ezekiel Elliott*,DAL,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3,2,14,NaN,NaN,258,311.7,319.7,284.7,117,4,5

In [12]:
df_2019_data["Year"] = '2019'
df_2019_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Christian McCaffrey*+,CAR,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1,0,19,1,NaN,355,471.2,477.2,413.2,215,1,1,2019
1,2,Lamar Jackson*+,BAL,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9,2,7,NaN,NaN,416,415.7,429.7,421.7,152,1,2,2019
2,3,Derrick Henry *,TEN,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5,3,18,NaN,NaN,277,294.6,303.6,285.6,136,2,3,2019
3,4,Aaron Jones,GNB,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3,2,19,NaN,NaN,266,314.8,322.8,290.3,125,3,4,2019
4,5,Ezekiel Elliott*,DAL,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3,2,14,NaN,NaN,258,311.7,319.7,284.7,117,4,5,2019

In [13]:
df_2019_data = df_2019_data[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'Y/A', 'TD', 'Tgt', 'Rec', 'Yds', 'Y/R',
       'TD', 'Fmb', 'FL', 'TD', '2PM', '2PP', 'FantPt', 'PPR', 'DKPt', 'FDPt',
       'VBD', 'PosRank', 'OvRank']]
df_2019_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey*+,CAR,2019,RB,23,16,16,0,2,287,0,1387,1005,0,15,4,19,0,2,287,0,1387,1005,4.83,0,15,4,19,142,116,0,1387,1005,8.66,0,15,4,19,1,0,0,15,4,19,1,NaN,355,471.2,477.2,413.2,215,1,1
1,2,Lamar Jackson*+,BAL,2019,QB,22,15,15,265,401,176,3127,1206,0,36,7,0,7,6,401,176,3127,1206,0,6.85,36,7,0,7,0,0,3127,1206,0,NaN,36,7,0,7,9,2,36,7,0,7,NaN,NaN,416,415.7,429.7,421.7,152,1,2
2,3,Derrick Henry *,TEN,2019,RB,25,15,15,0,0,303,0,1540,206,0,16,2,18,0,0,303,0,1540,206,5.08,0,16,2,18,24,18,0,1540,206,11.44,0,16,2,18,5,3,0,16,2,18,NaN,NaN,277,294.6,303.6,285.6,136,2,3
3,4,Aaron Jones,GNB,2019,RB,25,16,16,0,0,236,0,1084,474,0,16,3,19,0,0,236,0,1084,474,4.59,0,16,3,19,68,49,0,1084,474,9.67,0,16,3,19,3,2,0,16,3,19,NaN,NaN,266,314.8,322.8,290.3,125,3,4
4,5,Ezekiel Elliott*,DAL,2019,RB,24,16,16,0,0,301,0,1357,420,0,12,2,14,0,0,301,0,1357,420,4.51,0,12,2,14,71,54,0,1357,420,7.78,0,12,2,14,3,2,0,12,2,14,NaN,NaN,258,311.7,319.7,284.7,117,4,5

In [14]:
for char1 in spec_chars:
    df_2019_data['Player'] = df_2019_data['Player'].str.replace(char1, ' ')

In [15]:
df_2019_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,287,0,1387,1005,0,15,4,19,0,2,287,0,1387,1005,4.83,0,15,4,19,142,116,0,1387,1005,8.66,0,15,4,19,1,0,0,15,4,19,1,NaN,355,471.2,477.2,413.2,215,1,1
1,2,Lamar Jackson,BAL,2019,QB,22,15,15,265,401,176,3127,1206,0,36,7,0,7,6,401,176,3127,1206,0,6.85,36,7,0,7,0,0,3127,1206,0,NaN,36,7,0,7,9,2,36,7,0,7,NaN,NaN,416,415.7,429.7,421.7,152,1,2
2,3,Derrick Henry,TEN,2019,RB,25,15,15,0,0,303,0,1540,206,0,16,2,18,0,0,303,0,1540,206,5.08,0,16,2,18,24,18,0,1540,206,11.44,0,16,2,18,5,3,0,16,2,18,NaN,NaN,277,294.6,303.6,285.6,136,2,3
3,4,Aaron Jones,GNB,2019,RB,25,16,16,0,0,236,0,1084,474,0,16,3,19,0,0,236,0,1084,474,4.59,0,16,3,19,68,49,0,1084,474,9.67,0,16,3,19,3,2,0,16,3,19,NaN,NaN,266,314.8,322.8,290.3,125,3,4
4,5,Ezekiel Elliott,DAL,2019,RB,24,16,16,0,0,301,0,1357,420,0,12,2,14,0,0,301,0,1357,420,4.51,0,12,2,14,71,54,0,1357,420,7.78,0,12,2,14,3,2,0,12,2,14,NaN,NaN,258,311.7,319.7,284.7,117,4,5

In [16]:
#df_2018 = pd.read_csv('Resources/FF_Stats_2018.csv')
#df_2018.head()
URL = "https://www.pro-football-reference.com/years/2018/fantasy.htm"
df_2018 = pd.read_html(URL, match = 'Fantasy Rankings')

In [17]:
#converting table into pandas dataframe and droping extra header column
df_2018[0]
df_2018_data = pd.DataFrame(data=df_2018[0])
df_2018_data.columns = df_2018_data.columns.droplevel(0)
df_2018_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Todd Gurley*+,LAR,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3,NaN,313,372.1,379.1,342.6,178,1,1
1,2,Saquon Barkley*,NYG,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1,NaN,295,385.8,391.8,340.3,159,2,2
2,3,Christian McCaffrey,CAR,RB,22,16,16,1,1,50,1,0,219,1098,5.01,7,124,107,867,8.10,6,4,1,13,NaN,NaN,279,385.5,392.5,332.0,143,3,3
3,4,Alvin Kamara*,NOR,RB,23,15,13,0,0,0,0,0,194,883,4.55,14,105,81,709,8.75,4,1,0,18,3,NaN,273,354.2,360.2,313.7,138,4,4
4,5,Patrick Mahomes*+,KAN,QB,23,16,16,383,580,5097,50,12,60,272,4.53,2,0,0,0,NaN,0,9,2,2,1,NaN,417,417.1,437.1,429.1,134,1,5

In [19]:
df_2018_data["Year"] = '2018'
df_2018_data.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,Year
0,1,Todd Gurley*+,LAR,RB,24,14,14,0,0,0,0,0,256,1251,4.89,17,81,59,580,9.83,4,1,1,21,3,NaN,313,372.1,379.1,342.6,178,1,1,2018
1,2,Saquon Barkley*,NYG,RB,21,16,16,0,0,0,0,0,261,1307,5.01,11,121,91,721,7.92,4,0,0,15,1,NaN,295,385.8,391.8,340.3,159,2,2,2018
2,3,Christian McCaffrey,CAR,RB,22,16,16,1,1,50,1,0,219,1098,5.01,7,124,107,867,8.10,6,4,1,13,NaN,NaN,279,385.5,392.5,332.0,143,3,3,2018
3,4,Alvin Kamara*,NOR,RB,23,15,13,0,0,0,0,0,194,883,4.55,14,105,81,709,8.75,4,1,0,18,3,NaN,273,354.2,360.2,313.7,138,4,4,2018
4,5,Patrick Mahomes*+,KAN,QB,23,16,16,383,580,5097,50,12,60,272,4.53,2,0,0,0,NaN,0,9,2,2,1,NaN,417,417.1,437.1,429.1,134,1,5,2018

In [20]:
df_2018_data = df_2018_data[['Rk', 'Player', 'Tm', 'Year', 'FantPos', 'Age', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'Y/A', 'TD', 'Tgt', 'Rec', 'Yds', 'Y/R',
       'TD', 'Fmb', 'FL', 'TD', '2PM', '2PP', 'FantPt', 'PPR', 'DKPt', 'FDPt',
       'VBD', 'PosRank', 'OvRank']]
df_2018_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Todd Gurley*+,LAR,2018,RB,24,14,14,0,0,256,0,1251,580,0,17,4,21,0,0,256,0,1251,580,4.89,0,17,4,21,81,59,0,1251,580,9.83,0,17,4,21,1,1,0,17,4,21,3,NaN,313,372.1,379.1,342.6,178,1,1
1,2,Saquon Barkley*,NYG,2018,RB,21,16,16,0,0,261,0,1307,721,0,11,4,15,0,0,261,0,1307,721,5.01,0,11,4,15,121,91,0,1307,721,7.92,0,11,4,15,0,0,0,11,4,15,1,NaN,295,385.8,391.8,340.3,159,2,2
2,3,Christian McCaffrey,CAR,2018,RB,22,16,16,1,1,219,50,1098,867,1,7,6,13,0,1,219,50,1098,867,5.01,1,7,6,13,124,107,50,1098,867,8.10,1,7,6,13,4,1,1,7,6,13,NaN,NaN,279,385.5,392.5,332.0,143,3,3
3,4,Alvin Kamara*,NOR,2018,RB,23,15,13,0,0,194,0,883,709,0,14,4,18,0,0,194,0,883,709,4.55,0,14,4,18,105,81,0,883,709,8.75,0,14,4,18,1,0,0,14,4,18,3,NaN,273,354.2,360.2,313.7,138,4,4
4,5,Patrick Mahomes*+,KAN,2018,QB,23,16,16,383,580,60,5097,272,0,50,2,0,2,12,580,60,5097,272,0,4.53,50,2,0,2,0,0,5097,272,0,NaN,50,2,0,2,9,2,50,2,0,2,1,NaN,417,417.1,437.1,429.1,134,1,5

In [21]:
for char2 in spec_chars:
    df_2018_data['Player'] = df_2018_data['Player'].str.replace(char2, ' ')

C:\Users\duclu\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
df_2018_data.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Todd Gurley,LAR,2018,RB,24,14,14,0,0,256,0,1251,580,0,17,4,21,0,0,256,0,1251,580,4.89,0,17,4,21,81,59,0,1251,580,9.83,0,17,4,21,1,1,0,17,4,21,3,NaN,313,372.1,379.1,342.6,178,1,1
1,2,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,261,0,1307,721,0,11,4,15,0,0,261,0,1307,721,5.01,0,11,4,15,121,91,0,1307,721,7.92,0,11,4,15,0,0,0,11,4,15,1,NaN,295,385.8,391.8,340.3,159,2,2
2,3,Christian McCaffrey,CAR,2018,RB,22,16,16,1,1,219,50,1098,867,1,7,6,13,0,1,219,50,1098,867,5.01,1,7,6,13,124,107,50,1098,867,8.10,1,7,6,13,4,1,1,7,6,13,NaN,NaN,279,385.5,392.5,332.0,143,3,3
3,4,Alvin Kamara,NOR,2018,RB,23,15,13,0,0,194,0,883,709,0,14,4,18,0,0,194,0,883,709,4.55,0,14,4,18,105,81,0,883,709,8.75,0,14,4,18,1,0,0,14,4,18,3,NaN,273,354.2,360.2,313.7,138,4,4
4,5,Patrick Mahomes,KAN,2018,QB,23,16,16,383,580,60,5097,272,0,50,2,0,2,12,580,60,5097,272,0,4.53,50,2,0,2,0,0,5097,272,0,NaN,50,2,0,2,9,2,50,2,0,2,1,NaN,417,417.1,437.1,429.1,134,1,5

In [23]:
all_df = [df_2020_data,df_2019_data,df_2018_data]
merge_df = pd.concat(all_df)
merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,378,0,2027,114,0,17,0,17,0,0,378,0,2027,114,5.36,0,17,0,17,31,19,0,2027,114,6.00,0,17,0,17,3,2,0,17,0,17,1,NaN,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,187,0,932,756,0,16,5,21,0,0,187,0,932,756,4.98,0,16,5,21,107,83,0,932,756,9.11,0,16,5,21,1,0,0,16,5,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,312,0,1557,361,0,16,1,17,0,0,312,0,1557,361,4.99,0,16,1,17,54,44,0,1557,361,8.20,0,16,1,17,5,3,0,16,1,17,3,NaN,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce,KAN,2020,TE,31,15,15,1,2,0,4,0,1416,0,0,11,11,0,2,0,4,0,1416,NaN,0,0,11,11,145,105,4,0,1416,13.49,0,0,11,11,1,1,0,0,11,11,1,NaN,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,1374,0,0,18,18,0,0,0,0,0,1374,NaN,0,0,18,18,149,115,0,0,1374,11.95,0,0,18,18,1,1,0,0,18,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5

In [24]:
merge_df.count()

Rk         1922
Player     1922
Tm         1922
Year       1922
FantPos    1746
Age        1922
G          1922
GS         1922
Cmp        1922
Att        1922
Att        1922
Yds        1922
Yds        1922
Yds        1922
TD         1922
TD         1922
TD         1922
TD         1922
Int        1922
Att        1922
Att        1922
Yds        1922
Yds        1922
Yds        1922
Y/A        1066
TD         1922
TD         1922
TD         1922
TD         1922
Tgt        1922
Rec        1922
Yds        1922
Yds        1922
Yds        1922
Y/R        1507
TD         1922
TD         1922
TD         1922
TD         1922
Fmb        1922
FL         1922
TD         1922
TD         1922
TD         1922
TD         1922
2PM         219
2PP         140
FantPt     1716
PPR        1749
DKPt       1749
FDPt       1750
VBD         280
PosRank    1922
OvRank      294
dtype: int64

In [25]:
new_merge_df = merge_df.fillna(0)
new_merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,378,0,2027,114,0,17,0,17,0,0,378,0,2027,114,5.36,0,17,0,17,31,19,0,2027,114,6.00,0,17,0,17,3,2,0,17,0,17,1,0,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,187,0,932,756,0,16,5,21,0,0,187,0,932,756,4.98,0,16,5,21,107,83,0,932,756,9.11,0,16,5,21,1,0,0,16,5,21,0,0,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook,MIN,2020,RB,25,14,14,0,0,312,0,1557,361,0,16,1,17,0,0,312,0,1557,361,4.99,0,16,1,17,54,44,0,1557,361,8.20,0,16,1,17,5,3,0,16,1,17,3,0,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce,KAN,2020,TE,31,15,15,1,2,0,4,0,1416,0,0,11,11,0,2,0,4,0,1416,0,0,0,11,11,145,105,4,0,1416,13.49,0,0,11,11,1,1,0,0,11,11,1,0,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams,GNB,2020,WR,28,14,14,0,0,0,0,0,1374,0,0,18,18,0,0,0,0,0,1374,0,0,0,18,18,149,115,0,0,1374,11.95,0,0,18,18,1,1,0,0,18,18,0,0,243,358.4,362.4,300.9,117,1,5

In [26]:
new_merge_df=new_merge_df.sort_index(ascending=True)
new_merge_df.head()

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry,TEN,2020,RB,26,16,16,0,0,378,0,2027,114,0,17,0,17,0,0,378,0,2027,114,5.36,0,17,0,17,31,19,0,2027,114,6.00,0,17,0,17,3,2,0,17,0,17,1,0,314,333.1,341.1,323.6,184,1,1
0,1,Todd Gurley,LAR,2018,RB,24,14,14,0,0,256,0,1251,580,0,17,4,21,0,0,256,0,1251,580,4.89,0,17,4,21,81,59,0,1251,580,9.83,0,17,4,21,1,1,0,17,4,21,3,0,313,372.1,379.1,342.6,178,1,1
0,1,Christian McCaffrey,CAR,2019,RB,23,16,16,0,2,287,0,1387,1005,0,15,4,19,0,2,287,0,1387,1005,4.83,0,15,4,19,142,116,0,1387,1005,8.66,0,15,4,19,1,0,0,15,4,19,1,0,355,471.2,477.2,413.2,215,1,1
1,2,Alvin Kamara,NOR,2020,RB,25,15,10,0,0,187,0,932,756,0,16,5,21,0,0,187,0,932,756,4.98,0,16,5,21,107,83,0,932,756,9.11,0,16,5,21,1,0,0,16,5,21,0,0,295,377.8,383.8,336.3,165,2,2
1,2,Saquon Barkley,NYG,2018,RB,21,16,16,0,0,261,0,1307,721,0,11,4,15,0,0,261,0,1307,721,5.01,0,11,4,15,121,91,0,1307,721,7.92,0,11,4,15,0,0,0,11,4,15,1,0,295,385.8,391.8,340.3,159,2,2

In [ ]:
#new_merge_df = new_merge_df.drop(columns='Rk')
##new_merge_df.head()

In [27]:
new_merge_df.Player = new_merge_df.Player.str.rstrip()

In [ ]:
#new_merge_df.reset_index(drop=True)

In [28]:
#Type in player name
x = input("Enter Player Name:")
if ((new_merge_df['Player']==x)).any():
    print("Done")
else:
    print('Check Spelling')

Enter Player Name:Kyler Murray
Done

In [29]:
#Type in player name
y = input("Enter Player Name:")
if ((new_merge_df['Player']==y)).any():
    print("Done")
else:
    print('Check Spelling')

Enter Player Name:Matthew Stafford
Done

In [30]:
player_input_1 = new_merge_df.loc[new_merge_df.loc[:,"Player"] == x, :].sort_values(by=['Year'])
player_input_1

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
50,50,Kyler Murray,ARI,2019,QB,22,16,16,349,542,93,3722,544,0,20,4,0,4,12,542,93,3722,544,0,5.85,20,4,0,4,0,0,3722,544,0,0,20,4,0,4,5,2,20,4,0,4,0,3,285,285.3,305.3,297.3,22,8,50
8,9,Kyler Murray,ARI,2020,QB,23,16,16,375,558,133,3971,819,0,26,11,0,11,12,558,133,3971,819,0,6.16,26,11,0,11,0,0,3971,819,0,0,26,11,0,11,9,4,26,11,0,11,0,0,379,378.7,400.7,390.7,96,3,9

In [31]:
player_input_2 = new_merge_df.loc[new_merge_df.loc[:,"Player"] == y, :].sort_values(by=['Year'])
player_input_2

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
87,86,Matthew Stafford,DET,2018,QB,30,16,16,367,555,25,3777,71,0,21,0,0,0,11,555,25,3777,71,0,2.84,21,0,0,0,0,0,3777,71,0,0,21,0,0,0,6,4,21,0,0,0,0,0,212,212.2,230.2,223.2,0,20,0
98,96,Matthew Stafford,DET,2019,QB,31,8,8,187,291,20,2499,66,0,19,0,0,0,5,291,20,2499,66,0,3.30,19,0,0,0,0,0,2499,66,0,0,19,0,0,0,5,3,19,0,0,0,0,0,167,166.6,177.6,171.6,0,29,0
82,81,Matthew Stafford,DET,2020,QB,32,16,16,339,528,29,4084,112,0,26,0,0,0,10,528,29,4084,112,0,3.86,26,0,0,0,1,0,4084,112,0,0,26,0,0,0,2,1,26,0,0,0,0,2,261,260.6,277.6,270.6,0,15,0

In [32]:
players=[player_input_1, player_input_2]
player_merge = pd.concat(players)
player_merge

,Rk,Player,Tm,Year,FantPos,Age,G,GS,Cmp,Att,Att,Yds,Yds,Yds,TD,TD,TD,TD,Int,Att,Att,Yds,Yds,Yds,Y/A,TD,TD,TD,TD,Tgt,Rec,Yds,Yds,Yds,Y/R,TD,TD,TD,TD,Fmb,FL,TD,TD,TD,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
50,50,Kyler Murray,ARI,2019,QB,22,16,16,349,542,93,3722,544,0,20,4,0,4,12,542,93,3722,544,0,5.85,20,4,0,4,0,0,3722,544,0,0,20,4,0,4,5,2,20,4,0,4,0,3,285,285.3,305.3,297.3,22,8,50
8,9,Kyler Murray,ARI,2020,QB,23,16,16,375,558,133,3971,819,0,26,11,0,11,12,558,133,3971,819,0,6.16,26,11,0,11,0,0,3971,819,0,0,26,11,0,11,9,4,26,11,0,11,0,0,379,378.7,400.7,390.7,96,3,9
87,86,Matthew Stafford,DET,2018,QB,30,16,16,367,555,25,3777,71,0,21,0,0,0,11,555,25,3777,71,0,2.84,21,0,0,0,0,0,3777,71,0,0,21,0,0,0,6,4,21,0,0,0,0,0,212,212.2,230.2,223.2,0,20,0
98,96,Matthew Stafford,DET,2019,QB,31,8,8,187,291,20,2499,66,0,19,0,0,0,5,291,20,2499,66,0,3.30,19,0,0,0,0,0,2499,66,0,0,19,0,0,0,5,3,19,0,0,0,0,0,167,166.6,177.6,171.6,0,29,0
82,81,Matthew Stafford,DET,2020,QB,32,16,16,339,528,29,4084,112,0,26,0,0,0,10,528,29,4084,112,0,3.86,26,0,0,0,1,0,4084,112,0,0,26,0,0,0,2,1,26,0,0,0,0,2,261,260.6,277.6,270.6,0,15,0

In [ ]:
#player_stats_df = pd.DataFrame(data=new_merge_df)
#player_stats_df.head()

In [ ]:
#player_stats_df = player_stats_df.set_index('Player')
#player_stats_df.head()

In [ ]:
# Saving as a csv to convert into JSON data
#player_stats_df.to_csv('player_stats.csv')

In [ ]:
#player_stats_df.columns

In [ ]:
#Use these lines to scrap the for data so you dont have to save files
#df.columns = df.columns.droplevel(0)
#with open('my_file.csv', 'wb') as f:
    #writer = csv.writer(f)
    #writer.writerows(data)