In [2]:
from bs4 import BeautifulSoup
import requests
import smtplib
import time
import datetime
import pandas as pd

In [15]:
pd.set_option('display.max_columns', None)

In [16]:
# Website
URL = "https://www.pro-football-reference.com/years/2020/fantasy.htm"
df = pd.read_html(URL)[0]
df.head(100)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Rk             Player                 Tm
0                   1   Derrick Henry *+                TEN
1                   2     Alvin Kamara *                NOR
2                   3       Dalvin Cook*                MIN
3                   4     Travis Kelce*+                KAN
4                   5    Davante Adams*+                GNB
..                ...                ...                ...
95                 93  Mitchell Trubisky                CHI
96                 94   Ryan Fitzpatrick                MIA
97                 95        Andy Dalton                DAL
98                 96       Dak Prescott                DAL
99                 97     Tua Tagovailoa                MIA

   Unnamed: 3_level_0 Unnamed: 4_level_0 Games     Passing                     \
              FantPos                Age     G  GS     Cmp  Att   Yds  TD Int
0                  RB                 26    16  16       0    0     0   0   0
1                  RB                 25    15  10       0    0     0   0   0
2                  RB                 25    14  14       0    0     0   0   0
3                  TE                 31    15  15       1    2     4   0   0
4                  WR                 28    14  14       0    0     0   0   0
..                ...                ...   ...  ..     ...  ...   ...  ..  ..
95                 QB                 26    10   9     199  297  2055  16   8
96                 QB                 38     9   7     183  267  2091  13   8
97                 QB                 33    11   9     216  333  2170  14   8
98                 QB                 27     5   5     151  222  1856   9   4
99                 QB                 22    10   9     186  290  1814  11   5

   Rushing                 Receiving                       Fumbles    Scoring  \
       Att   Yds   Y/A  TD       Tgt  Rec   Yds    Y/R  TD     Fmb FL      TD
0      378  2027  5.36  17        31   19   114   6.00   0       3  2      17
1      187   932  4.98  16       107   83   756   9.11   5       1  0      21
2      312  1557  4.99  16        54   44   361   8.20   1       5  3      17
3        0     0   NaN   0       145  105  1416  13.49  11       1  1      11
4        0     0   NaN   0       149  115  1374  11.95  18       1  1      18
..     ...   ...   ...  ..       ...  ...   ...    ...  ..     ... ..     ...
95      33   195  5.91   1         0    0     0    NaN   0       6  2       1
96      30   151  5.03   2         1    1     0   0.00   0       2  0       2
97      28   114  4.07   0         1    1    -3  -3.00   0       2  1       0
98      18    93  5.17   3         1    1    11  11.00   1       3  3       4
99      36   109  3.03   3         0    0     0    NaN   0       1  1       3

             Fantasy
    2PM  2PP  FantPt    PPR   DKPt   FDPt  VBD PosRank OvRank
0     1  NaN     314  333.1  341.1  323.6  184       1      1
1   NaN  NaN     295  377.8  383.8  336.3  165       2      2
2     3  NaN     294  337.8  346.8  315.8  164       3      3
3     1  NaN     208  312.8  316.8  260.3  117       1      4
4   NaN  NaN     243  358.4  362.4  300.9  117       1      5
..  ...  ...     ...    ...    ...    ...  ...     ...    ...
95  NaN    1     154  153.7  169.7  161.7  NaN      27    NaN
96    1    2     153  153.7  167.7  161.2  NaN      28    NaN
97  NaN  NaN     136  136.9  151.9  144.4  NaN      29    NaN
98    1    1     135  135.6  145.6  139.1  NaN      31    NaN
99  NaN    1     135  135.5  147.5  140.5  NaN      30    NaN

[100 rows x 33 columns]

In [17]:
df.columns

MultiIndex([('Unnamed: 0_level_0',      'Rk'),
            ('Unnamed: 1_level_0',  'Player'),
            ('Unnamed: 2_level_0',      'Tm'),
            ('Unnamed: 3_level_0', 'FantPos'),
            ('Unnamed: 4_level_0',     'Age'),
            (             'Games',       'G'),
            (             'Games',      'GS'),
            (           'Passing',     'Cmp'),
            (           'Passing',     'Att'),
            (           'Passing',     'Yds'),
            (           'Passing',      'TD'),
            (           'Passing',     'Int'),
            (           'Rushing',     'Att'),
            (           'Rushing',     'Yds'),
            (           'Rushing',     'Y/A'),
            (           'Rushing',      'TD'),
            (         'Receiving',     'Tgt'),
            (         'Receiving',     'Rec'),
            (         'Receiving',     'Yds'),
            (         'Receiving',     'Y/R'),
            (         'Receiving',      'TD'),
            (           'Fumbles',     'Fmb'),
            (           'Fumbles',      'FL'),
            (           'Scoring',      'TD'),
            (           'Scoring',     '2PM'),
            (           'Scoring',     '2PP'),
            (           'Fantasy',  'FantPt'),
            (           'Fantasy',     'PPR'),
            (           'Fantasy',    'DKPt'),
            (           'Fantasy',    'FDPt'),
            (           'Fantasy',     'VBD'),
            (           'Fantasy', 'PosRank'),
            (           'Fantasy',  'OvRank')],
           )

In [22]:
df.columns = df.columns.droplevel(0)

In [24]:
df.reset_index(drop=True)

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry *+,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3,2,17,1,NaN,314,333.1,341.1,323.6,184,1,1
1,2,Alvin Kamara *,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1,0,21,NaN,NaN,295,377.8,383.8,336.3,165,2,2
2,3,Dalvin Cook*,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5,3,17,3,NaN,294,337.8,346.8,315.8,164,3,3
3,4,Travis Kelce*+,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1,1,11,1,NaN,208,312.8,316.8,260.3,117,1,4
4,5,Davante Adams*+,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1,1,18,NaN,NaN,243,358.4,362.4,300.9,117,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,622,Andre Roberts*,BUF,WR,32,15,0,0,0,0,0,0,1,-3,-3.00,0,5,4,34,8.50,0,3,2,0,NaN,NaN,-1,3.1,5.1,1.1,NaN,245,NaN
642,623,Nate Sudfeld,PHI,QB,27,1,0,5,12,32,0,1,2,12,6.00,0,0,0,0,NaN,0,1,1,0,NaN,NaN,-2,-1.5,0.5,-0.5,NaN,81,NaN
643,624,Nsimba Webster,LAR,NaN,24,16,0,0,0,0,0,0,0,0,NaN,0,0,0,0,NaN,0,3,1,0,NaN,NaN,-2,-2.0,-1.0,-2.0,NaN,248,NaN
644,625,Dede Westbrook,JAX,WR,27,2,0,0,0,0,0,0,0,0,NaN,0,1,1,4,4.00,0,1,1,0,NaN,NaN,-2,-0.6,0.4,-1.1,NaN,247,NaN
645,626,Kendall Hinton,DEN,WR,23,1,0,1,9,13,0,2,2,7,3.50,0,0,0,0,NaN,0,0,0,0,NaN,NaN,-3,-2.8,-0.8,-0.8,NaN,249,NaN