In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
#Thursday Night Game
URL = "https://www.pro-football-reference.com/boxscores/202109090tam.htm#player_offense"
table = pd.read_html(URL, match = 'Passing, Rushing, & Receiving')
table[0]
df = pd.DataFrame(data=table[0])
df

    Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
                Player                 Tm      Cmp      Att      Yds       TD
0         Dak Prescott                DAL       42       58      403        3
1      Ezekiel Elliott                DAL        0        0        0        0
2         Tony Pollard                DAL        0        0        0        0
3         Amari Cooper                DAL        0        0        0        0
4          CeeDee Lamb                DAL        0        0        0        0
5       Dalton Schultz                DAL        0        0        0        0
6       Michael Gallup                DAL        0        0        0        0
7   Cedrick Wilson Jr.                DAL        0        0        0        0
8         Blake Jarwin                DAL        0        0        0        0
9                  NaN                NaN  Passing  Passing  Passing  Passing
10              Player                 Tm      Cmp      Att      Yds       TD
11           Tom Brady                TAM       32       50      379        4
12   Leonard Fournette                TAM        0        0        0        0
13     Ronald Jones II                TAM        0        0        0        0
14       Antonio Brown                TAM        0        0        0        0
15        Chris Godwin                TAM        0        0        0        0
16      Rob Gronkowski                TAM        0        0        0        0
17          Mike Evans                TAM        0        0        0        0
18     Giovani Bernard                TAM        0        0        0        0
19       Tyler Johnson                TAM        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         1        1       12       31    101.4        4       13        0
1         0        0        0        0      NaN       11       33        0
2         0        0        0        0      NaN        3       14        0
3         0        0        0        0      NaN        0        0        0
4         0        0        0        0      NaN        0        0        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9   Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
10      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
11        2        0        0       47     97.0        0        0        0
12        0        0        0        0      NaN        9       32        0
13        0        0        0        0      NaN        4       14        0
14        0        0        0        0      NaN        1        6        0
15        0        0        0        0      NaN        0        0        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         7          0          0          0          0          0        1
1        13          2          2          6          0          3        0
2        11          4          4         29          0         11        0
3         0         16         13        139          2         28        0
4         0         15          7        104          1         31        0
5         0          6          6         45          0         16        0
6         0          7          4         36          0         12        0
7         0          3          3         24          0         13        0
8         0          4          3         20          0          7        0
9   Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
10      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
11        0          0          0          0          0          0        0
12        7          7          5         27          0         10        0
13        5          0          0          0          0          0        1
14        6          7          5        121          1         47        0
15        0         14          9        105          1         24        1
16        0          8          8         90          2         20        0
17        0          6          3         24          0         10        0
18        0          3          2         12          0          8        0
19        0          1          0          0          0          0        0


         FL
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9   Fumbles
10       FL
11        0
12        0
13        1
14        0
15        1
16        0
17        0
18        0
19        0

In [4]:
df = df.drop([9,10])

In [5]:
df.columns = df.columns.droplevel(0)
df

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0
1,Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,NaN,11,33,0,13,2,2,6,0,3,0,0
2,Tony Pollard,DAL,0,0,0,0,0,0,0,0,NaN,3,14,0,11,4,4,29,0,11,0,0
3,Amari Cooper,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,16,13,139,2,28,0,0
4,CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,15,7,104,1,31,0,0
5,Dalton Schultz,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,6,45,0,16,0,0
6,Michael Gallup,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,4,36,0,12,0,0
7,Cedrick Wilson Jr.,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,24,0,13,0,0
8,Blake Jarwin,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,20,0,7,0,0
11,Tom Brady,TAM,32,50,379,4,2,0,0,47,97.0,0,0,0,0,0,0,0,0,0,0,0
12,Leonard Fournette,TAM,0,0,0,0,0,0,0,0,NaN,9,32,0,7,7,5,27,0,10,0,0
13,Ronald Jones II,TAM,0,0,0,0,0,0,0,0,NaN,4,14,0,5,0,0,0,0,0,1,1
14,Antonio Brown,TAM,0,0,0,0,0,0,0,0,NaN,1,6,0,6,7,5,121,1,47,0,0
15,Chris Godwin,TAM,0,0,0,0,0,0,0,0,NaN,0,0,0,0,14,9,105,1,24,1,1
16,Rob Gronkowski,TAM,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,8,90,2,20,0,0
17,Mike Evans,TAM,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,24,0,10,0,0
18,Giovani Bernard,TAM,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,12,0,8,0,0
19,Tyler Johnson,TAM,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [6]:
#Sunday Games
URL_1 = "https://www.pro-football-reference.com/boxscores/202109120atl.htm#player_offense"
table_1 = pd.read_html(URL_1, match = 'Passing, Rushing, & Receiving')
table_1[0]
df1 = pd.DataFrame(data=table_1[0])
df1

       Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                   Player                 Tm      Cmp      Att      Yds
0             Jalen Hurts                PHI       27       35      264
1           Miles Sanders                PHI        0        0        0
2        Kenneth Gainwell                PHI        0        0        0
3           DeVonta Smith                PHI        0        0        0
4            Jalen Reagor                PHI        0        0        0
5          Dallas Goedert                PHI        0        0        0
6               Zach Ertz                PHI        0        0        0
7            Quez Watkins                PHI        0        0        0
8                     NaN                NaN  Passing  Passing  Passing
9                  Player                 Tm      Cmp      Att      Yds
10              Matt Ryan                ATL       21       35      164
11  Cordarrelle Patterson                ATL        0        0        0
12             Mike Davis                ATL        0        0        0
13            Keith Smith                ATL        0        0        0
14          Calvin Ridley                ATL        0        0        0
15             Kyle Pitts                ATL        0        0        0
16           Hayden Hurst                ATL        0        0        0
17           Russell Gage                ATL        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         3        0        1        3       28    126.4        7       62
1         0        0        0        0        0      NaN       15       74
2         0        0        0        0        0      NaN        9       37
3         0        0        0        0        0      NaN        0        0
4         0        0        0        0        0      NaN        0        0
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8   Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
9        TD      Int       Sk      Yds      Lng     Rate      Att      Yds
10        0        0        3       28       18     71.6        2        8
11        0        0        0        0        0      NaN        7       54
12        0        0        0        0        0      NaN       15       49
13        0        0        0        0        0      NaN        2       13
14        0        0        0        0        0      NaN        0        0
15        0        0        0        0        0      NaN        0        0
16        0        0        0        0        0      NaN        0        0
17        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0       14          0          0          0          0          0
1         0       23          5          4         39          0         25
2         1        8          3          2          6          0          9
3         0        0          8          6         71          1         19
4         0        0          6          6         49          1         23
5         0        0          5          4         42          1         13
6         0        0          2          2         34          0         28
7         0        0          3          3         23          0         11
8   Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
9        TD      Lng        Tgt        Rec        Yds         TD        Lng
10        0        8          0          0          0          0          0
11        0       14          2          2         13          0         12
12        0       12          6          3         23          0          9
13        0        8          3          3         18          0          9
14        0        0          8          5         51          0         16
15        0        0          8          4         31          0         18
16        0        0          4          4         28          0          9
17        0        0          2          0          0          0          0

    Fumbles
        Fmb       FL
0         1        0
1         0        0
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8   Fumbles  Fumbles
9       Fmb       FL
10        1        0
11        0        0
12        0        0
13        0        0
14        0        0
15        0        0
16        0        0
17        0        0

In [7]:
df1 = df1.drop([8,9])
df1.columns = df1.columns.droplevel(0)
df1

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Jalen Hurts,PHI,27,35,264,3,0,1,3,28,126.4,7,62,0,14,0,0,0,0,0,1,0
1,Miles Sanders,PHI,0,0,0,0,0,0,0,0,NaN,15,74,0,23,5,4,39,0,25,0,0
2,Kenneth Gainwell,PHI,0,0,0,0,0,0,0,0,NaN,9,37,1,8,3,2,6,0,9,0,0
3,DeVonta Smith,PHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,6,71,1,19,0,0
4,Jalen Reagor,PHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,6,49,1,23,0,0
5,Dallas Goedert,PHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,42,1,13,0,0
6,Zach Ertz,PHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,34,0,28,0,0
7,Quez Watkins,PHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,23,0,11,0,0
10,Matt Ryan,ATL,21,35,164,0,0,3,28,18,71.6,2,8,0,8,0,0,0,0,0,1,0
11,Cordarrelle Patterson,ATL,0,0,0,0,0,0,0,0,NaN,7,54,0,14,2,2,13,0,12,0,0
12,Mike Davis,ATL,0,0,0,0,0,0,0,0,NaN,15,49,0,12,6,3,23,0,9,0,0
13,Keith Smith,ATL,0,0,0,0,0,0,0,0,NaN,2,13,0,8,3,3,18,0,9,0,0
14,Calvin Ridley,ATL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,5,51,0,16,0,0
15,Kyle Pitts,ATL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,4,31,0,18,0,0
16,Hayden Hurst,ATL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,28,0,9,0,0
17,Russell Gage,ATL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0

In [8]:
#Sunday Games
URL_2 = 'https://www.pro-football-reference.com/boxscores/202109120buf.htm#player_offense'
table_2 = pd.read_html(URL_2, match = 'Passing, Rushing, & Receiving')
df2 = pd.DataFrame(data=table_2[0])

In [9]:
df2 = df2.drop([9,10])
df2.columns = df2.columns.droplevel(0)
df2

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Ben Roethlisberger,PIT,18,32,188,1,0,2,11,24,83.9,4,5,0,8,0,0,0,0,0,1,0
1,Najee Harris,PIT,0,0,0,0,0,0,0,0,NaN,16,45,0,18,3,1,4,0,4,0,0
2,Chase Claypool,PIT,0,0,0,0,0,0,0,0,NaN,1,25,0,25,5,3,45,0,22,0,0
3,JuJu Smith-Schuster,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,4,52,0,24,0,0
4,Diontae Johnson,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,10,5,36,1,14,0,0
5,Pat Freiermuth,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,24,0,24,0,0
6,Eric Ebron,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,19,0,19,0,0
7,James Washington,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,10,0,9,0,0
8,Zach Gentry,PIT,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,-2,0,-2,0,0
11,Josh Allen,BUF,30,51,270,1,0,3,16,37,79.7,9,44,0,11,0,0,0,0,0,2,1
12,Devin Singletary,BUF,0,0,0,0,0,0,0,0,NaN,11,72,0,25,5,3,8,0,5,2,0
13,Matt Breida,BUF,0,0,0,0,0,0,0,0,NaN,4,4,0,7,0,0,0,0,0,0,0
14,Stefon Diggs,BUF,0,0,0,0,0,0,0,0,NaN,0,0,0,0,14,9,69,0,13,0,0
15,Cole Beasley,BUF,0,0,0,0,0,0,0,0,NaN,0,0,0,0,13,8,60,0,12,0,0
16,Emmanuel Sanders,BUF,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,4,52,0,16,0,0
17,Dawson Knox,BUF,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,41,0,13,0,0
18,Gabriel Davis,BUF,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,2,40,1,37,0,0
19,Isaiah McKenzie,BUF,0,0,0,0,0,0,0,0,NaN,1,-3,0,-3,0,0,0,0,0,0,0

In [10]:
#Sunday Games
URL_3 = 'https://www.pro-football-reference.com/boxscores/202109120car.htm#player_offense'
table_3 = pd.read_html(URL_3, match = 'Passing, Rushing, & Receiving')
df3 = pd.DataFrame(data=table_3[0])
df3

      Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                  Player                 Tm      Cmp      Att      Yds
0            Zach Wilson                NYJ       20       37      258
1          Tevin Coleman                NYJ        0        0        0
2             Ty Johnson                NYJ        0        0        0
3         Michael Carter                NYJ        0        0        0
4            Corey Davis                NYJ        0        0        0
5        Braxton Berrios                NYJ        0        0        0
6            Denzel Mims                NYJ        0        0        0
7            Tyler Kroft                NYJ        0        0        0
8           Ryan Griffin                NYJ        0        0        0
9             Jeff Smith                NYJ        0        0        0
10          Elijah Moore                NYJ        0        0        0
11                   NaN                NaN  Passing  Passing  Passing
12                Player                 Tm      Cmp      Att      Yds
13           Sam Darnold                CAR       24       35      279
14   Christian McCaffrey                CAR        0        0        0
15            D.J. Moore                CAR        0        0        0
16        Robby Anderson                CAR        0        0        0
17  Terrace Marshall Jr.                CAR        0        0        0
18            Ian Thomas                CAR        0        0        0
19            Dan Arnold                CAR        0        0        0
20         Chuba Hubbard                CAR        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         2        1        6       51       40     82.9        0        0
1         0        0        0        0        0      NaN        9       24
2         0        0        0        0        0      NaN        4       15
3         0        0        0        0        0      NaN        4        6
4         0        0        0        0        0      NaN        0        0
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        0        0
10        0        0        0        0        0      NaN        0        0
11  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
12       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
13        1        0        1        9       57    102.0        5       -1
14        0        0        0        0        0      NaN       21       98
15        0        0        0        0        0      NaN        1       14
16        0        0        0        0        0      NaN        0        0
17        0        0        0        0        0      NaN        0        0
18        0        0        0        0        0      NaN        0        0
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0        0          0          0          0          0          0
1         0        9          0          0          0          0          0
2         0       12          3          1         11          0         11
3         0        2          2          1         14          0         14
4         0        0          7          5         97          2         35
5         0        0          7          5         51          0         25
6         0        0          1          1         40          0         40
7         0        0          5          3         26          0         10
8         0        0          6          3         22          0          8
9         0        0          1          0          0          0          0
10        0        0          4          1         -3          0         -3
11  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
12       TD      Lng        Tgt        Rec        Yds         TD        Lng
13        1        5          0          0          0          0          0
14        0       18          9          9         89          0         22
15        0       14          8          6         80          0         27
16        0        0          3          1         57          1         57
17        0        0          6          3         26          0         11
18        0        0          2          1         17          0         17
19        0        0          3          2          6          0          5
20        0        0          2          2          4          0          3

    Fumbles
        Fmb       FL
0         1        0
1         0        0
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         0        0
10        0        0
11  Fumbles  Fumbles
12      Fmb       FL
13        1        1
14        0        0
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0

In [11]:
df3 = df3.drop([11,12])
df3.columns = df3.columns.droplevel(0)
df3

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Zach Wilson,NYJ,20,37,258,2,1,6,51,40,82.9,0,0,0,0,0,0,0,0,0,1,0
1,Tevin Coleman,NYJ,0,0,0,0,0,0,0,0,NaN,9,24,0,9,0,0,0,0,0,0,0
2,Ty Johnson,NYJ,0,0,0,0,0,0,0,0,NaN,4,15,0,12,3,1,11,0,11,0,0
3,Michael Carter,NYJ,0,0,0,0,0,0,0,0,NaN,4,6,0,2,2,1,14,0,14,0,0
4,Corey Davis,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,97,2,35,0,0
5,Braxton Berrios,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,51,0,25,0,0
6,Denzel Mims,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,40,0,40,0,0
7,Tyler Kroft,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,3,26,0,10,0,0
8,Ryan Griffin,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,22,0,8,0,0
9,Jeff Smith,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
10,Elijah Moore,NYJ,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,1,-3,0,-3,0,0
13,Sam Darnold,CAR,24,35,279,1,0,1,9,57,102.0,5,-1,1,5,0,0,0,0,0,1,1
14,Christian McCaffrey,CAR,0,0,0,0,0,0,0,0,NaN,21,98,0,18,9,9,89,0,22,0,0
15,D.J. Moore,CAR,0,0,0,0,0,0,0,0,NaN,1,14,0,14,8,6,80,0,27,0,0
16,Robby Anderson,CAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,57,1,57,0,0
17,Terrace Marshall Jr.,CAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,26,0,11,0,0
18,Ian Thomas,CAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,17,0,17,0,0
19,Dan Arnold,CAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,6,0,5,0,0
20,Chuba Hubbard,CAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,4,0,3,0,0

In [12]:
#Sunday Games
URL_4 = 'https://www.pro-football-reference.com/boxscores/202109120cin.htm#player_offense'
table_4 = pd.read_html(URL_4, match = 'Passing, Rushing, & Receiving')
df4 = pd.DataFrame(data=table_4[0])
df4

    Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
                Player                 Tm      Cmp      Att      Yds       TD
0         Kirk Cousins                MIN       36       49      351        2
1     Justin Jefferson                MIN        1        1       11        0
2          Dalvin Cook                MIN        0        0        0        0
3       Ameer Abdullah                MIN        0        0        0        0
4   Alexander Mattison                MIN        0        0        0        0
5         Adam Thielen                MIN        0        0        0        0
6          K.J. Osborn                MIN        0        0        0        0
7        Tyler Conklin                MIN        0        0        0        0
8       Dede Westbrook                MIN        0        0        0        0
9             C.J. Ham                MIN        0        0        0        0
10       Chris Herndon                MIN        0        0        0        0
11                 NaN                NaN  Passing  Passing  Passing  Passing
12              Player                 Tm      Cmp      Att      Yds       TD
13          Joe Burrow                CIN       20       27      261        2
14           Joe Mixon                CIN        0        0        0        0
15       Samaje Perine                CIN        0        0        0        0
16         Tee Higgins                CIN        0        0        0        0
17         C.J. Uzomah                CIN        0        0        0        0
18          Tyler Boyd                CIN        0        0        0        0
19         Mike Thomas                CIN        0        0        0        0
20       Ja'Marr Chase                CIN        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         0        3       26       34    106.8        0        0        0
1         0        0        0       11    112.5        0        0        0
2         0        0        0        0      NaN       20       61        1
3         0        0        0        0      NaN        1        4        0
4         0        0        0        0      NaN        1        2        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        0        0        0
10        0        0        0        0      NaN        0        0        0
11  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
12      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
13        0        5       44       50    128.8        1        2        0
14        0        0        0        0      NaN       29      127        1
15        0        0        0        0      NaN        5       22        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0
20        0        0        0        0      NaN        1       -2        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         0          0          0          0          0          0        0
1         0          9          5         71          0         34        0
2        17          7          6         43          0          9        1
3         4          2          2         15          0         10        0
4         2          1          1          4          0          4        0
5         0         10          9         92          2         24        0
6         0          9          7         76          0         25        0
7         0          4          4         41          0         27        0
8         0          1          1         11          0         11        0
9         0          2          2          9          0          6        0
10        0          2          0          0          0          0        0
11  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
12      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
13        2          0          0          0          0          0        0
14       19          4          4         23          0         12        0
15       13          1          1          7          0          7        0
16        0          5          4         58          1         28        0
17        0          2          2         35          0         32        0
18        0          4          3         32          0         18        0
19        0          3          1          5          0          5        0
20       -2          7          5        101          1         50        0


         FL
0         0
1         0
2         1
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11  Fumbles
12       FL
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0

In [13]:
df4 = df4.drop([11,12])
df4.columns = df4.columns.droplevel(0)
df4

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Kirk Cousins,MIN,36,49,351,2,0,3,26,34,106.8,0,0,0,0,0,0,0,0,0,0,0
1,Justin Jefferson,MIN,1,1,11,0,0,0,0,11,112.5,0,0,0,0,9,5,71,0,34,0,0
2,Dalvin Cook,MIN,0,0,0,0,0,0,0,0,NaN,20,61,1,17,7,6,43,0,9,1,1
3,Ameer Abdullah,MIN,0,0,0,0,0,0,0,0,NaN,1,4,0,4,2,2,15,0,10,0,0
4,Alexander Mattison,MIN,0,0,0,0,0,0,0,0,NaN,1,2,0,2,1,1,4,0,4,0,0
5,Adam Thielen,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,10,9,92,2,24,0,0
6,K.J. Osborn,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,7,76,0,25,0,0
7,Tyler Conklin,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,41,0,27,0,0
8,Dede Westbrook,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,11,0,11,0,0
9,C.J. Ham,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,9,0,6,0,0
10,Chris Herndon,MIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0
13,Joe Burrow,CIN,20,27,261,2,0,5,44,50,128.8,1,2,0,2,0,0,0,0,0,0,0
14,Joe Mixon,CIN,0,0,0,0,0,0,0,0,NaN,29,127,1,19,4,4,23,0,12,0,0
15,Samaje Perine,CIN,0,0,0,0,0,0,0,0,NaN,5,22,0,13,1,1,7,0,7,0,0
16,Tee Higgins,CIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,58,1,28,0,0
17,C.J. Uzomah,CIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,35,0,32,0,0
18,Tyler Boyd,CIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,32,0,18,0,0
19,Mike Thomas,CIN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,5,0,5,0,0
20,Ja'Marr Chase,CIN,0,0,0,0,0,0,0,0,NaN,1,-2,0,-2,7,5,101,1,50,0,0

In [14]:
#Sunday Games
URL_5 = 'https://www.pro-football-reference.com/boxscores/202109120clt.htm#player_offense'
table_5 = pd.read_html(URL_5, match = 'Passing, Rushing, & Receiving')
df5 = pd.DataFrame(data=table_5[0])
df5

     Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                 Player                 Tm      Cmp      Att      Yds
0        Russell Wilson                SEA       18       23      254
1          Chris Carson                SEA        0        0        0
2      D'Wayne Eskridge                SEA        0        0        0
3         Rashaad Penny                SEA        0        0        0
4         DeeJay Dallas                SEA        0        0        0
5         Freddie Swain                SEA        0        0        0
6         Tyler Lockett                SEA        0        0        0
7          D.K. Metcalf                SEA        0        0        0
8           Will Dissly                SEA        0        0        0
9        Gerald Everett                SEA        0        0        0
10                  NaN                NaN  Passing  Passing  Passing
11               Player                 Tm      Cmp      Att      Yds
12         Carson Wentz                IND       25       38      251
13      Jonathan Taylor                IND        0        0        0
14         Nyheim Hines                IND        0        0        0
15          Zach Pascal                IND        0        0        0
16  Michael Pittman Jr.                IND        0        0        0
17        Mike Strachan                IND        0        0        0
18      Parris Campbell                IND        0        0        0
19           Jack Doyle                IND        0        0        0
20          Mo Alie-Cox                IND        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         4        0        3       13       69    152.3        5        9
1         0        0        0        0        0      NaN       16       91
2         0        0        0        0        0      NaN        2       22
3         0        0        0        0        0      NaN        2        8
4         0        0        0        0        0      NaN        1        5
5         0        0        0        0        0      NaN        1        5
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        0        0
10  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
11       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
12        2        0        3       28       24    102.0        4       23
13        0        0        0        0        0      NaN       17       56
14        0        0        0        0        0      NaN        9       34
15        0        0        0        0        0      NaN        0        0
16        0        0        0        0        0      NaN        0        0
17        0        0        0        0        0      NaN        0        0
18        0        0        0        0        0      NaN        0        0
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0       11          0          0          0          0          0
1         0       33          3          3         26          0         16
2         0       13          1          1          6          0          6
3         0        4          0          0          0          0          0
4         0        5          1          1          5          0          5
5         0        5          1          0          0          0          0
6         0        0          5          4        100          2         69
7         0        0          5          4         60          1         30
8         0        0          3          3         37          0         22
9         0        0          2          2         20          1         11
10  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
11       TD      Lng        Tgt        Rec        Yds         TD        Lng
12        0        8          0          0          0          0          0
13        0       12          7          6         60          0         15
14        0        8          8          6         48          0         19
15        0        0          5          4         43          2         16
16        0        0          4          3         29          0         14
17        0        0          2          2         26          0         16
18        0        0          3          1         24          0         24
19        0        0          4          3         21          0          9
20        0        0          2          0          0          0          0

    Fumbles
        Fmb       FL
0         0        0
1         1        1
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         0        0
10  Fumbles  Fumbles
11      Fmb       FL
12        1        1
13        0        0
14        0        0
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0

In [15]:
df5 = df5.drop([10,11])
df5.columns = df5.columns.droplevel(0)
df5

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Russell Wilson,SEA,18,23,254,4,0,3,13,69,152.3,5,9,0,11,0,0,0,0,0,0,0
1,Chris Carson,SEA,0,0,0,0,0,0,0,0,NaN,16,91,0,33,3,3,26,0,16,1,1
2,D'Wayne Eskridge,SEA,0,0,0,0,0,0,0,0,NaN,2,22,0,13,1,1,6,0,6,0,0
3,Rashaad Penny,SEA,0,0,0,0,0,0,0,0,NaN,2,8,0,4,0,0,0,0,0,0,0
4,DeeJay Dallas,SEA,0,0,0,0,0,0,0,0,NaN,1,5,0,5,1,1,5,0,5,0,0
5,Freddie Swain,SEA,0,0,0,0,0,0,0,0,NaN,1,5,0,5,1,0,0,0,0,0,0
6,Tyler Lockett,SEA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,100,2,69,0,0
7,D.K. Metcalf,SEA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,60,1,30,0,0
8,Will Dissly,SEA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,37,0,22,0,0
9,Gerald Everett,SEA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,20,1,11,0,0
12,Carson Wentz,IND,25,38,251,2,0,3,28,24,102.0,4,23,0,8,0,0,0,0,0,1,1
13,Jonathan Taylor,IND,0,0,0,0,0,0,0,0,NaN,17,56,0,12,7,6,60,0,15,0,0
14,Nyheim Hines,IND,0,0,0,0,0,0,0,0,NaN,9,34,0,8,8,6,48,0,19,0,0
15,Zach Pascal,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,43,2,16,0,0
16,Michael Pittman Jr.,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,29,0,14,0,0
17,Mike Strachan,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,26,0,16,0,0
18,Parris Campbell,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,24,0,24,0,0
19,Jack Doyle,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,21,0,9,0,0
20,Mo Alie-Cox,IND,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0

In [16]:
#Sunday Games
URL_6 = 'https://www.pro-football-reference.com/boxscores/202109120det.htm#player_offense'
table_6 = pd.read_html(URL_6, match = 'Passing, Rushing, & Receiving')
df6 = pd.DataFrame(data=table_6[0])
df6

   Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
               Player                 Tm      Cmp      Att      Yds       TD
0     Jimmy Garoppolo                SFO       17       25      314        1
1          Trey Lance                SFO        1        1        5        1
2     Elijah Mitchell                SFO        0        0        0        0
3      Raheem Mostert                SFO        0        0        0        0
4       Jamycal Hasty                SFO        0        0        0        0
5        Deebo Samuel                SFO        0        0        0        0
6       George Kittle                SFO        0        0        0        0
7     Trent Sherfield                SFO        0        0        0        0
8       Kyle Juszczyk                SFO        0        0        0        0
9        Mohamed Sanu                SFO        0        0        0        0
10                NaN                NaN  Passing  Passing  Passing  Passing
11             Player                 Tm      Cmp      Att      Yds       TD
12         Jared Goff                DET       38       57      338        3
13    Jamaal Williams                DET        0        0        0        0
14      D'Andre Swift                DET        0        0        0        0
15      Kalif Raymond                DET        0        0        0        0
16     T.J. Hockenson                DET        0        0        0        0
17  Amon-Ra St. Brown                DET        0        0        0        0
18     Trinity Benson                DET        0        0        0        0
19    Tyrell Williams                DET        0        0        0        0
20     Quintez Cephus                DET        0        0        0        0
21       Darren Fells                DET        0        0        0        0
22      Jason Cabinda                DET        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         0        1        8       79    124.2        3        2        0
1         0        0        0        5    127.1        3        2        0
2         0        0        0        0      NaN       19      104        1
3         0        0        0        0      NaN        2       20        0
4         0        0        0        0      NaN        1        3        1
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        0        0        0
10  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
11      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
12        1        3       24       43     92.6        3       14        0
13        0        0        0        0      NaN        9       54        1
14        0        0        0        0      NaN       11       39        0
15        0        0        0        0      NaN        1        9        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0
20        0        0        0        0      NaN        0        0        0
21        0        0        0        0      NaN        0        0        0
22        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         3          0          0          0          0          0        1
1         2          0          0          0          0          0        0
2        38          0          0          0          0          0        0
3        11          0          0          0          0          0        0
4         3          1          1         15          0         15        0
5         0         12          9        189          1         79        1
6         0          5          4         78          0         35        0
7         0          3          2         23          1         18        0
8         0          1          1          7          0          7        0
9         0          1          1          7          0          7        0
10  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
11      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
12       10          0          0          0          0          0        0
13       20          9          8         56          0         11        0
14       16         11          8         65          1         43        0
15        9          4          3         50          0         25        0
16        0         10          8         97          1         23        0
17        0          4          2         23          0         20        0
18        0          6          3         19          0         11        0
19        0          3          2         14          0          7        0
20        0          7          3         12          1          7        0
21        0          1          1          2          0          2        0
22        0          1          0          0          0          0        0


         FL
0         1
1         0
2         0
3         0
4         0
5         1
6         0
7         0
8         0
9         0
10  Fumbles
11       FL
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0

In [17]:
df6 = df6.drop([10,11])
df6.columns = df6.columns.droplevel(0)
df6

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Jimmy Garoppolo,SFO,17,25,314,1,0,1,8,79,124.2,3,2,0,3,0,0,0,0,0,1,1
1,Trey Lance,SFO,1,1,5,1,0,0,0,5,127.1,3,2,0,2,0,0,0,0,0,0,0
2,Elijah Mitchell,SFO,0,0,0,0,0,0,0,0,NaN,19,104,1,38,0,0,0,0,0,0,0
3,Raheem Mostert,SFO,0,0,0,0,0,0,0,0,NaN,2,20,0,11,0,0,0,0,0,0,0
4,Jamycal Hasty,SFO,0,0,0,0,0,0,0,0,NaN,1,3,1,3,1,1,15,0,15,0,0
5,Deebo Samuel,SFO,0,0,0,0,0,0,0,0,NaN,0,0,0,0,12,9,189,1,79,1,1
6,George Kittle,SFO,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,78,0,35,0,0
7,Trent Sherfield,SFO,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,23,1,18,0,0
8,Kyle Juszczyk,SFO,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,7,0,7,0,0
9,Mohamed Sanu,SFO,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,7,0,7,0,0
12,Jared Goff,DET,38,57,338,3,1,3,24,43,92.6,3,14,0,10,0,0,0,0,0,0,0
13,Jamaal Williams,DET,0,0,0,0,0,0,0,0,NaN,9,54,1,20,9,8,56,0,11,0,0
14,D'Andre Swift,DET,0,0,0,0,0,0,0,0,NaN,11,39,0,16,11,8,65,1,43,0,0
15,Kalif Raymond,DET,0,0,0,0,0,0,0,0,NaN,1,9,0,9,4,3,50,0,25,0,0
16,T.J. Hockenson,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,10,8,97,1,23,0,0
17,Amon-Ra St. Brown,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,2,23,0,20,0,0
18,Trinity Benson,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,19,0,11,0,0
19,Tyrell Williams,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,14,0,7,0,0
20,Quintez Cephus,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,3,12,1,7,0,0
21,Darren Fells,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,2,0,2,0,0
22,Jason Cabinda,DET,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [18]:
#Sunday Games
URL_7 = 'https://www.pro-football-reference.com/boxscores/202109120htx.htm#player_offense'
table_7 = pd.read_html(URL_7, match = 'Passing, Rushing, & Receiving')
df7 = pd.DataFrame(data=table_7[0])
df7

      Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                  Player                 Tm      Cmp      Att      Yds
0        Trevor Lawrence                JAX       28       51      332
1            Carlos Hyde                JAX        0        0        0
2         James Robinson                JAX        0        0        0
3   Laviska Shenault Jr.                JAX        0        0        0
4               DJ Chark                JAX        0        0        0
5           Marvin Jones                JAX        0        0        0
6    James O'Shaughnessy                JAX        0        0        0
7         Chris Manhertz                JAX        0        0        0
8          Tyron Johnson                JAX        0        0        0
9            Devin Smith                JAX        0        0        0
10                   NaN                NaN  Passing  Passing  Passing
11                Player                 Tm      Cmp      Att      Yds
12          Tyrod Taylor                HOU       21       33      291
13           Mark Ingram                HOU        0        0        0
14       Phillip Lindsay                HOU        0        0        0
15         David Johnson                HOU        0        0        0
16         Brandin Cooks                HOU        0        0        0
17         Pharaoh Brown                HOU        0        0        0
18        Danny Amendola                HOU        0        0        0
19          Chris Conley                HOU        0        0        0
20          Nico Collins                HOU        0        0        0
21          Rex Burkhead                HOU        0        0        0
22          Jordan Akins                HOU        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         3        3        1       13       41     70.1        1       -2
1         0        0        0        0        0      NaN        9       44
2         0        0        0        0        0      NaN        5       25
3         0        0        0        0        0      NaN        1        9
4         0        0        0        0        0      NaN        0        0
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        0        0
10  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
11       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
12        2        0        1        2       52    112.1        4       40
13        0        0        0        0        0      NaN       26       85
14        0        0        0        0        0      NaN        8       25
15        0        0        0        0        0      NaN        3       10
16        0        0        0        0        0      NaN        0        0
17        0        0        0        0        0      NaN        0        0
18        0        0        0        0        0      NaN        0        0
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0
21        0        0        0        0        0      NaN        0        0
22        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0       -2          0          0          0          0          0
1         0       13          2          2         14          0          9
2         0        7          6          3         29          0         15
3         0        9          9          7         50          0         14
4         0        0         12          3         86          1         41
5         0        0          9          5         77          1         33
6         0        0          8          6         48          0         22
7         0        0          1          1         22          1         22
8         0        0          1          1          6          0          6
9         0        0          1          0          0          0          0
10  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
11       TD      Lng        Tgt        Rec        Yds         TD        Lng
12        0       29          0          0          0          0          0
13        1       11          1          0          0          0          0
14        1        8          1          0          0          0          0
15        0        5          4          3         18          1          9
16        0        0          7          5        132          0         52
17        0        0          5          4         67          0         29
18        0        0          5          5         34          1          8
19        0        0          2          2         27          0         17
20        0        0          3          1          7          0          7
21        0        0          2          1          6          0          6
22        0        0          2          0          0          0          0

    Fumbles
        Fmb       FL
0         0        0
1         0        0
2         1        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         0        0
10  Fumbles  Fumbles
11      Fmb       FL
12        1        0
13        0        0
14        0        0
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0
21        0        0
22        0        0

In [19]:
df7 = df7.drop([10,11])
df7.columns = df7.columns.droplevel(0)
df7

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Trevor Lawrence,JAX,28,51,332,3,3,1,13,41,70.1,1,-2,0,-2,0,0,0,0,0,0,0
1,Carlos Hyde,JAX,0,0,0,0,0,0,0,0,NaN,9,44,0,13,2,2,14,0,9,0,0
2,James Robinson,JAX,0,0,0,0,0,0,0,0,NaN,5,25,0,7,6,3,29,0,15,1,0
3,Laviska Shenault Jr.,JAX,0,0,0,0,0,0,0,0,NaN,1,9,0,9,9,7,50,0,14,0,0
4,DJ Chark,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,12,3,86,1,41,0,0
5,Marvin Jones,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,5,77,1,33,0,0
6,James O'Shaughnessy,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,6,48,0,22,0,0
7,Chris Manhertz,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,22,1,22,0,0
8,Tyron Johnson,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,6,0,6,0,0
9,Devin Smith,JAX,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
12,Tyrod Taylor,HOU,21,33,291,2,0,1,2,52,112.1,4,40,0,29,0,0,0,0,0,1,0
13,Mark Ingram,HOU,0,0,0,0,0,0,0,0,NaN,26,85,1,11,1,0,0,0,0,0,0
14,Phillip Lindsay,HOU,0,0,0,0,0,0,0,0,NaN,8,25,1,8,1,0,0,0,0,0,0
15,David Johnson,HOU,0,0,0,0,0,0,0,0,NaN,3,10,0,5,4,3,18,1,9,0,0
16,Brandin Cooks,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,132,0,52,0,0
17,Pharaoh Brown,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,67,0,29,0,0
18,Danny Amendola,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,5,34,1,8,0,0
19,Chris Conley,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,27,0,17,0,0
20,Nico Collins,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,7,0,7,0,0
21,Rex Burkhead,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,6,0,6,0,0
22,Jordan Akins,HOU,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0

In [20]:
#Sunday Games
URL_8 = 'https://www.pro-football-reference.com/boxscores/202109120kan.htm#player_offense'
table_8 = pd.read_html(URL_8, match = 'Passing, Rushing, & Receiving')
df8 = pd.DataFrame(data=table_8[0])
df8

       Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                   Player                 Tm      Cmp      Att      Yds
0          Baker Mayfield                CLE       21       28      321
1              Nick Chubb                CLE        0        0        0
2             Kareem Hunt                CLE        0        0        0
3        Anthony Schwartz                CLE        0        0        0
4           Jarvis Landry                CLE        0        0        0
5             David Njoku                CLE        0        0        0
6           Austin Hooper                CLE        0        0        0
7         Harrison Bryant                CLE        0        0        0
8   Donovan Peoples-Jones                CLE        0        0        0
9            Jamie Gillan                CLE        0        0        0
10          Andy Janovich                CLE        0        0        0
11                    NaN                NaN  Passing  Passing  Passing
12                 Player                 Tm      Cmp      Att      Yds
13        Patrick Mahomes                KAN       27       36      337
14  Clyde Edwards-Helaire                KAN        0        0        0
15            Tyreek Hill                KAN        0        0        0
16        Darrel Williams                KAN        0        0        0
17             Blake Bell                KAN        0        0        0
18         Michael Burton                KAN        0        0        0
19           Travis Kelce                KAN        0        0        0
20         Mecole Hardman                KAN        0        0        0
21      Demarcus Robinson                KAN        0        0        0
22          Byron Pringle                KAN        0        0        0
23           Mike Remmers                KAN        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         0        1        2       17       44     97.5        1        7
1         0        0        0        0        0      NaN       15       83
2         0        0        0        0        0      NaN        6       33
3         0        0        0        0        0      NaN        1       17
4         0        0        0        0        0      NaN        2       13
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        1        0
10        0        0        0        0        0      NaN        0        0
11  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
12       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
13        3        0        2       13       75    131.4        5       18
14        0        0        0        0        0      NaN       14       43
15        0        0        0        0        0      NaN        1        4
16        0        0        0        0        0      NaN        1        4
17        0        0        0        0        0      NaN        1        2
18        0        0        0        0        0      NaN        1        2
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0
21        0        0        0        0        0      NaN        0        0
22        0        0        0        0        0      NaN        0        0
23        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0        7          0          0         11          0          0
1         2       18          2          2         18          0         10
2         1       15          3          3         28          0         19
3         0       17          5          3         69          0         44
4         1        8          5          5         71          0         32
5         0        0          5          3         76          0         43
6         0        0          3          3         27          0         14
7         0        0          2          1         17          0         17
8         0        0          1          1          4          0          4
9         0       -8          0          0          0          0          0
10        0        0          1          0          0          0          0
11  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
12       TD      Lng        Tgt        Rec        Yds         TD        Lng
13        1        8          0          0          0          0          0
14        0        9          3          3         29          0         14
15        0        4         15         11        197          1         75
16        0        4          0          0          0          0          0
17        0        2          1          1          3          0          3
18        0        2          0          0          0          0          0
19        0        0          7          6         76          2         19
20        0        0          3          3         19          0          8
21        0        0          2          1          9          0          9
22        0        0          2          1          6          0          6
23        0        0          1          1         -2          0         -2

    Fumbles
        Fmb       FL
0         0        0
1         1        1
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         1        0
10        0        0
11  Fumbles  Fumbles
12      Fmb       FL
13        0        0
14        0        0
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0
21        0        0
22        0        0
23        0        0

In [21]:
df8 = df8.drop([11,12])
df8.columns = df8.columns.droplevel(0)
df8

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Baker Mayfield,CLE,21,28,321,0,1,2,17,44,97.5,1,7,0,7,0,0,11,0,0,0,0
1,Nick Chubb,CLE,0,0,0,0,0,0,0,0,NaN,15,83,2,18,2,2,18,0,10,1,1
2,Kareem Hunt,CLE,0,0,0,0,0,0,0,0,NaN,6,33,1,15,3,3,28,0,19,0,0
3,Anthony Schwartz,CLE,0,0,0,0,0,0,0,0,NaN,1,17,0,17,5,3,69,0,44,0,0
4,Jarvis Landry,CLE,0,0,0,0,0,0,0,0,NaN,2,13,1,8,5,5,71,0,32,0,0
5,David Njoku,CLE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,3,76,0,43,0,0
6,Austin Hooper,CLE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,27,0,14,0,0
7,Harrison Bryant,CLE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,17,0,17,0,0
8,Donovan Peoples-Jones,CLE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,4,0,4,0,0
9,Jamie Gillan,CLE,0,0,0,0,0,0,0,0,NaN,1,0,0,-8,0,0,0,0,0,1,0
10,Andy Janovich,CLE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
13,Patrick Mahomes,KAN,27,36,337,3,0,2,13,75,131.4,5,18,1,8,0,0,0,0,0,0,0
14,Clyde Edwards-Helaire,KAN,0,0,0,0,0,0,0,0,NaN,14,43,0,9,3,3,29,0,14,0,0
15,Tyreek Hill,KAN,0,0,0,0,0,0,0,0,NaN,1,4,0,4,15,11,197,1,75,0,0
16,Darrel Williams,KAN,0,0,0,0,0,0,0,0,NaN,1,4,0,4,0,0,0,0,0,0,0
17,Blake Bell,KAN,0,0,0,0,0,0,0,0,NaN,1,2,0,2,1,1,3,0,3,0,0
18,Michael Burton,KAN,0,0,0,0,0,0,0,0,NaN,1,2,0,2,0,0,0,0,0,0,0
19,Travis Kelce,KAN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,6,76,2,19,0,0
20,Mecole Hardman,KAN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,19,0,8,0,0
21,Demarcus Robinson,KAN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,9,0,9,0,0
22,Byron Pringle,KAN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,6,0,6,0,0
23,Mike Remmers,KAN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,-2,0,-2,0,0

In [22]:
#Sunday Games
URL_9 = 'https://www.pro-football-reference.com/boxscores/202109120nor.htm#player_offense'
table_9 = pd.read_html(URL_9, match = 'Passing, Rushing, & Receiving')
df9 = pd.DataFrame(data=table_9[0])
df9

          Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                      Player                 Tm      Cmp      Att      Yds
0              Aaron Rodgers                GNB       15       28      133
1                Jordan Love                GNB        5        7       68
2                  AJ Dillon                GNB        0        0        0
3                 Kylin Hill                GNB        0        0        0
4                Aaron Jones                GNB        0        0        0
5               Randall Cobb                GNB        0        0        0
6              Davante Adams                GNB        0        0        0
7              Amari Rodgers                GNB        0        0        0
8             Marcedes Lewis                GNB        0        0        0
9   Marquez Valdes-Scantling                GNB        0        0        0
10              Allen Lazard                GNB        0        0        0
11              Malik Taylor                GNB        0        0        0
12             Robert Tonyan                GNB        0        0        0
13                       NaN                NaN  Passing  Passing  Passing
14                    Player                 Tm      Cmp      Att      Yds
15            Jameis Winston                NOR       14       20      148
16               Taysom Hill                NOR        1        1        3
17              Alvin Kamara                NOR        0        0        0
18                Tony Jones                NOR        0        0        0
19             Deonte Harris                NOR        0        0        0
20             Juwan Johnson                NOR        0        0        0
21             Adam Trautman                NOR        0        0        0
22          Marquez Callaway                NOR        0        0        0
23               Chris Hogan                NOR        0        0        0
24             Ty Montgomery                NOR        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         0        2        1       11       31     36.8        0        0
1         0        0        1        4       32    102.1        0        0
2         0        0        0        0        0      NaN        4       19
3         0        0        0        0        0      NaN        5       14
4         0        0        0        0        0      NaN        5        9
5         0        0        0        0        0      NaN        1        1
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        0        0
10        0        0        0        0        0      NaN        0        0
11        0        0        0        0        0      NaN        0        0
12        0        0        0        0        0      NaN        0        0
13  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
14       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
15        5        0        0        0       55    130.8        6       37
16        0        0        0        0        3     79.2        2        1
17        0        0        0        0        0      NaN       20       83
18        0        0        0        0        0      NaN       11       50
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0
21        0        0        0        0        0      NaN        0        0
22        0        0        0        0        0      NaN        0        0
23        0        0        0        0        0      NaN        0        0
24        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         0        0          0          0          0          0          0
1         0        0          0          0          0          0          0
2         0        6          2          1          7          0          7
3         0        8          0          0          0          0          0
4         0        3          2          2         13          0          7
5         0        1          1          1         32          0         32
6         0        0          7          5         56          0         31
7         0        0          1          1         19          0         19
8         0        0          1          1         19          0         19
9         0        0          8          3         17          0         10
10        0        0          4          2         16          0         14
11        0        0          3          2         14          0          7
12        0        0          4          2          8          0          5
13  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
14       TD      Lng        Tgt        Rec        Yds         TD        Lng
15        0       15          0          0          0          0          0
16        0        2          0          0          0          0          0
17        0       14          4          3          8          1          3
18        0        9          1          1          3          0          3
19        0        0          2          2         72          1         55
20        0        0          3          3         21          2         12
21        0        0          6          3         18          0          8
22        0        0          2          1         14          0         14
23        0        0          1          1         10          1         10
24        0        0          1          1          5          0          5

    Fumbles
        Fmb       FL
0         0        0
1         1        1
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         0        0
10        0        0
11        0        0
12        0        0
13  Fumbles  Fumbles
14      Fmb       FL
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0
21        0        0
22        0        0
23        0        0
24        0        0

In [23]:
df9 = df9.drop([13,14])
df9.columns = df9.columns.droplevel(0)
df9

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Aaron Rodgers,GNB,15,28,133,0,2,1,11,31,36.8,0,0,0,0,0,0,0,0,0,0,0
1,Jordan Love,GNB,5,7,68,0,0,1,4,32,102.1,0,0,0,0,0,0,0,0,0,1,1
2,AJ Dillon,GNB,0,0,0,0,0,0,0,0,NaN,4,19,0,6,2,1,7,0,7,0,0
3,Kylin Hill,GNB,0,0,0,0,0,0,0,0,NaN,5,14,0,8,0,0,0,0,0,0,0
4,Aaron Jones,GNB,0,0,0,0,0,0,0,0,NaN,5,9,0,3,2,2,13,0,7,0,0
5,Randall Cobb,GNB,0,0,0,0,0,0,0,0,NaN,1,1,0,1,1,1,32,0,32,0,0
6,Davante Adams,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,56,0,31,0,0
7,Amari Rodgers,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,19,0,19,0,0
8,Marcedes Lewis,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,19,0,19,0,0
9,Marquez Valdes-Scantling,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,3,17,0,10,0,0
10,Allen Lazard,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,2,16,0,14,0,0
11,Malik Taylor,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,14,0,7,0,0
12,Robert Tonyan,GNB,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,2,8,0,5,0,0
15,Jameis Winston,NOR,14,20,148,5,0,0,0,55,130.8,6,37,0,15,0,0,0,0,0,0,0
16,Taysom Hill,NOR,1,1,3,0,0,0,0,3,79.2,2,1,0,2,0,0,0,0,0,0,0
17,Alvin Kamara,NOR,0,0,0,0,0,0,0,0,NaN,20,83,0,14,4,3,8,1,3,0,0
18,Tony Jones,NOR,0,0,0,0,0,0,0,0,NaN,11,50,0,9,1,1,3,0,3,0,0
19,Deonte Harris,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,72,1,55,0,0
20,Juwan Johnson,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,21,2,12,0,0
21,Adam Trautman,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,18,0,8,0,0
22,Marquez Callaway,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,14,0,14,0,0
23,Chris Hogan,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,10,1,10,0,0
24,Ty Montgomery,NOR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,5,0,5,0,0

In [24]:
#Sunday Games
URL_10 = 'https://www.pro-football-reference.com/boxscores/202109120nwe.htm#player_offense'
table_10 = pd.read_html(URL_10, match = 'Passing, Rushing, & Receiving')
df10 = pd.DataFrame(data=table_10[0])
df10

     Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                 Player                 Tm      Cmp      Att      Yds
0        Tua Tagovailoa                MIA       16       27      202
1          Myles Gaskin                MIA        0        0        0
2         Malcolm Brown                MIA        0        0        0
3          Salvon Ahmed                MIA        0        0        0
4       Jacoby Brissett                MIA        0        0        0
5        DeVante Parker                MIA        0        0        0
6         Jaylen Waddle                MIA        0        0        0
7         Durham Smythe                MIA        0        0        0
8         Albert Wilson                MIA        0        0        0
9          Mike Gesicki                MIA        0        0        0
10                  NaN                NaN  Passing  Passing  Passing
11               Player                 Tm      Cmp      Att      Yds
12            Mac Jones                NWE       29       39      281
13        Damien Harris                NWE        0        0        0
14          James White                NWE        0        0        0
15          Jonnu Smith                NWE        0        0        0
16       Brandon Bolden                NWE        0        0        0
17  Rhamondre Stevenson                NWE        0        0        0
18       Nelson Agholor                NWE        0        0        0
19        Jakobi Meyers                NWE        0        0        0
20         Hunter Henry                NWE        0        0        0
21      Kendrick Bourne                NWE        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         1        1        2       17       36     79.6        4        1
1         0        0        0        0        0      NaN        9       49
2         0        0        0        0        0      NaN        5       16
3         0        0        0        0        0      NaN        3        4
4         0        0        0        0        0      NaN        2        4
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9         0        0        0        0        0      NaN        0        0
10  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
11       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
12        1        0        1       13       26    102.6        0        0
13        0        0        0        0        0      NaN       23      100
14        0        0        0        0        0      NaN        4       12
15        0        0        0        0        0      NaN        1        6
16        0        0        0        0        0      NaN        1        5
17        0        0        0        0        0      NaN        1        2
18        0        0        0        0        0      NaN        0        0
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0
21        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         1        3          0          0          0          0          0
1         0       15          5          5         27          0         12
2         0        5          0          0          0          0          0
3         0        8          3          2         24          0         18
4         0        2          0          0          0          0          0
5         0        0          7          4         81          0         30
6         0        0          6          4         61          1         36
7         0        0          2          1          9          0          9
8         0        0          2          0          0          0          0
9         0        0          2          0          0          0          0
10  Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
11       TD      Lng        Tgt        Rec        Yds         TD        Lng
12        0        0          0          0          0          0          0
13        0       35          3          2         17          0          9
14        0       10          7          6         49          0         26
15        0        6          5          5         42          0         11
16        0        5          0          0          0          0          0
17        0        2          1          1          9          0          9
18        0        0          7          5         72          1         25
19        0        0          9          6         44          0         22
20        0        0          3          3         31          0         16
21        0        0          3          1         17          0         17

    Fumbles
        Fmb       FL
0         0        0
1         0        0
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9         0        0
10  Fumbles  Fumbles
11      Fmb       FL
12        1        0
13        1        1
14        0        0
15        1        0
16        0        0
17        1        1
18        0        0
19        0        0
20        0        0
21        0        0

In [25]:
df10 = df10.drop([10,11])
df10.columns = df10.columns.droplevel(0)
df10

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Tua Tagovailoa,MIA,16,27,202,1,1,2,17,36,79.6,4,1,1,3,0,0,0,0,0,0,0
1,Myles Gaskin,MIA,0,0,0,0,0,0,0,0,NaN,9,49,0,15,5,5,27,0,12,0,0
2,Malcolm Brown,MIA,0,0,0,0,0,0,0,0,NaN,5,16,0,5,0,0,0,0,0,0,0
3,Salvon Ahmed,MIA,0,0,0,0,0,0,0,0,NaN,3,4,0,8,3,2,24,0,18,0,0
4,Jacoby Brissett,MIA,0,0,0,0,0,0,0,0,NaN,2,4,0,2,0,0,0,0,0,0,0
5,DeVante Parker,MIA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,4,81,0,30,0,0
6,Jaylen Waddle,MIA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,4,61,1,36,0,0
7,Durham Smythe,MIA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,9,0,9,0,0
8,Albert Wilson,MIA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0
9,Mike Gesicki,MIA,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,0,0,0,0,0,0
12,Mac Jones,NWE,29,39,281,1,0,1,13,26,102.6,0,0,0,0,0,0,0,0,0,1,0
13,Damien Harris,NWE,0,0,0,0,0,0,0,0,NaN,23,100,0,35,3,2,17,0,9,1,1
14,James White,NWE,0,0,0,0,0,0,0,0,NaN,4,12,0,10,7,6,49,0,26,0,0
15,Jonnu Smith,NWE,0,0,0,0,0,0,0,0,NaN,1,6,0,6,5,5,42,0,11,1,0
16,Brandon Bolden,NWE,0,0,0,0,0,0,0,0,NaN,1,5,0,5,0,0,0,0,0,0,0
17,Rhamondre Stevenson,NWE,0,0,0,0,0,0,0,0,NaN,1,2,0,2,1,1,9,0,9,1,1
18,Nelson Agholor,NWE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,72,1,25,0,0
19,Jakobi Meyers,NWE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,6,44,0,22,0,0
20,Hunter Henry,NWE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,31,0,16,0,0
21,Kendrick Bourne,NWE,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,17,0,17,0,0

In [26]:
#Sunday Games
URL_11 = 'https://www.pro-football-reference.com/boxscores/202109120nyg.htm#player_offense'
table_11 = pd.read_html(URL_11, match = 'Passing, Rushing, & Receiving')
df11 = pd.DataFrame(data=table_11[0])
df11

    Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
                Player                 Tm      Cmp      Att      Yds       TD
0    Teddy Bridgewater                DEN       28       36      264        2
1        Melvin Gordon                DEN        0        0        0        0
2     Javonte Williams                DEN        0        0        0        0
3          Jerry Jeudy                DEN        0        0        0        0
4            Noah Fant                DEN        0        0        0        0
5            KJ Hamler                DEN        0        0        0        0
6          Tim Patrick                DEN        0        0        0        0
7   Albert Okwuegbunam                DEN        0        0        0        0
8     Courtland Sutton                DEN        0        0        0        0
9         Eric Saubert                DEN        0        0        0        0
10                 NaN                NaN  Passing  Passing  Passing  Passing
11              Player                 Tm      Cmp      Att      Yds       TD
12        Daniel Jones                NYG       22       37      267        1
13      Saquon Barkley                NYG        0        0        0        0
14     Devontae Booker                NYG        0        0        0        0
15    Sterling Shepard                NYG        0        0        0        0
16      Darius Slayton                NYG        0        0        0        0
17      Kenny Golladay                NYG        0        0        0        0
18        Kyle Rudolph                NYG        0        0        0        0
19     Gary Brightwell                NYG        0        0        0        0
20          C.J. Board                NYG        0        0        0        0
21       Elijhaa Penny                NYG        0        0        0        0
22      Kadarius Toney                NYG        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         0        2        9       25    115.7        3       19        0
1         0        0        0        0      NaN       11      101        1
2         0        0        0        0      NaN       14       45        0
3         0        0        0        0      NaN        0        0        0
4         0        0        0        0      NaN        0        0        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        0        0        0
10  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
11      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
12        0        2       13       42     90.7        6       27        1
13        0        0        0        0      NaN       10       26        0
14        0        0        0        0      NaN        4        7        0
15        0        0        0        0      NaN        0        0        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0
20        0        0        0        0      NaN        0        0        0
21        0        0        0        0      NaN        0        0        0
22        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         8          0          0          0          0          0        0
1        70          3          3         17          0         13        0
2        12          1          1         -4          0         -4        0
3         0          7          6         72          0         20        0
4         0          8          6         62          0         25        0
5         0          4          3         41          0         22        0
6         0          4          4         39          1         16        0
7         0          3          3         16          1          6        1
8         0          3          1         14          0         14        0
9         0          2          1          7          0          7        0
10  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
11      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
12        8          0          0          0          0          0        1
13        5          3          1          1          0          1        0
14        6          1          1          6          0          6        0
15        0          9          7        113          1         37        0
16        0          7          3         65          0         42        0
17        0          6          4         64          0         17        0
18        0          5          2          8          0          6        0
19        0          1          1          6          0          6        0
20        0          1          1          6          0          6        0
21        0          1          0          0          0          0        0
22        0          2          2         -2          0          4        0


         FL
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         1
8         0
9         0
10  Fumbles
11       FL
12        1
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0

In [27]:
df11 = df11.drop([10,11])
df11.columns = df11.columns.droplevel(0)
df11

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Teddy Bridgewater,DEN,28,36,264,2,0,2,9,25,115.7,3,19,0,8,0,0,0,0,0,0,0
1,Melvin Gordon,DEN,0,0,0,0,0,0,0,0,NaN,11,101,1,70,3,3,17,0,13,0,0
2,Javonte Williams,DEN,0,0,0,0,0,0,0,0,NaN,14,45,0,12,1,1,-4,0,-4,0,0
3,Jerry Jeudy,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,6,72,0,20,0,0
4,Noah Fant,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,6,62,0,25,0,0
5,KJ Hamler,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,41,0,22,0,0
6,Tim Patrick,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,39,1,16,0,0
7,Albert Okwuegbunam,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,16,1,6,1,1
8,Courtland Sutton,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,1,14,0,14,0,0
9,Eric Saubert,DEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,7,0,7,0,0
12,Daniel Jones,NYG,22,37,267,1,0,2,13,42,90.7,6,27,1,8,0,0,0,0,0,1,1
13,Saquon Barkley,NYG,0,0,0,0,0,0,0,0,NaN,10,26,0,5,3,1,1,0,1,0,0
14,Devontae Booker,NYG,0,0,0,0,0,0,0,0,NaN,4,7,0,6,1,1,6,0,6,0,0
15,Sterling Shepard,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,7,113,1,37,0,0
16,Darius Slayton,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,3,65,0,42,0,0
17,Kenny Golladay,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,4,64,0,17,0,0
18,Kyle Rudolph,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,2,8,0,6,0,0
19,Gary Brightwell,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,6,0,6,0,0
20,C.J. Board,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,6,0,6,0,0
21,Elijhaa Penny,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
22,Kadarius Toney,NYG,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,-2,0,4,0,0

In [28]:
#Sunday Games
URL_12 = 'https://www.pro-football-reference.com/boxscores/202109120oti.htm#player_offense'
table_12 = pd.read_html(URL_12, match = 'Passing, Rushing, & Receiving')
df12 = pd.DataFrame(data=table_12[0])
df12

       Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                    \
                   Player                 Tm      Cmp      Att      Yds
0            Kyler Murray                ARI       21       32      289
1           Chase Edmonds                ARI        0        0        0
2            James Conner                ARI        0        0        0
3         DeAndre Hopkins                ARI        0        0        0
4          Christian Kirk                ARI        0        0        0
5           Rondale Moore                ARI        0        0        0
6              A.J. Green                ARI        0        0        0
7           Maxx Williams                ARI        0        0        0
8        Demetrius Harris                ARI        0        0        0
9                     NaN                NaN  Passing  Passing  Passing
10                 Player                 Tm      Cmp      Att      Yds
11         Ryan Tannehill                TEN       21       35      212
12        Matthias Farley                TEN        1        1        6
13          Derrick Henry                TEN        0        0        0
14       Jeremy McNichols                TEN        0        0        0
15          Mekhi Sargent                TEN        0        0        0
16         Chester Rogers                TEN        0        0        0
17             A.J. Brown                TEN        0        0        0
18            Julio Jones                TEN        0        0        0
19        Anthony Firkser                TEN        0        0        0
20  Nick Westbrook-Ikhine                TEN        0        0        0
21           Amani Hooker                TEN        0        0        0
22            Geoff Swaim                TEN        0        0        0

                                                          Rushing           \
         TD      Int       Sk    Yds.1      Lng     Rate      Att      Yds
0         4        1        2        9       38    121.0        5       20
1         0        0        0        0        0      NaN       12       63
2         0        0        0        0        0      NaN       16       53
3         0        0        0        0        0      NaN        0        0
4         0        0        0        0        0      NaN        0        0
5         0        0        0        0        0      NaN        0        0
6         0        0        0        0        0      NaN        0        0
7         0        0        0        0        0      NaN        0        0
8         0        0        0        0        0      NaN        0        0
9   Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing
10       TD      Int       Sk      Yds      Lng     Rate      Att      Yds
11        1        1        6       56       39     74.9        2       17
12        0        0        0        0        6     91.7        0        0
13        0        0        0        0        0      NaN       17       58
14        0        0        0        0        0      NaN        2        9
15        0        0        0        0        0      NaN        1        2
16        0        0        0        0        0      NaN        0        0
17        0        0        0        0        0      NaN        0        0
18        0        0        0        0        0      NaN        0        0
19        0        0        0        0        0      NaN        0        0
20        0        0        0        0        0      NaN        0        0
21        0        0        0        0        0      NaN        0        0
22        0        0        0        0        0      NaN        0        0

                      Receiving                                              \
         TD      Lng        Tgt        Rec        Yds         TD        Lng
0         1        8          0          0          0          0          0
1         0       16          4          4         43          0         36
2         0        8          0          0          0          0          0
3         0        0          8          6         83          2         38
4         0        0          5          5         70          2         26
5         0        0          5          4         68          0         29
6         0        0          6          2         25          0         21
7         0        0          1          0          0          0          0
8         0        0          3          0          0          0          0
9   Rushing  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving
10       TD      Lng        Tgt        Rec        Yds         TD        Lng
11        1       16          0          0          0          0          0
12        0        0          0          0          0          0          0
13        0       19          4          3         19          0          8
14        0        8          4          3         24          0          9
15        0        2          0          0          0          0          0
16        0        0          6          4         62          0         39
17        0        0          8          4         49          1         19
18        0        0          6          3         29          0         10
19        0        0          4          3         19          0         11
20        0        0          2          1         10          0         10
21        0        0          1          1          6          0          6
22        0        0          1          0          0          0          0

    Fumbles
        Fmb       FL
0         0        0
1         0        0
2         0        0
3         0        0
4         0        0
5         0        0
6         0        0
7         0        0
8         0        0
9   Fumbles  Fumbles
10      Fmb       FL
11        2        2
12        0        0
13        0        0
14        0        0
15        0        0
16        0        0
17        0        0
18        0        0
19        0        0
20        0        0
21        0        0
22        0        0

In [29]:
df12 = df12.drop([9,10])
df12.columns = df12.columns.droplevel(0)
df12

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Kyler Murray,ARI,21,32,289,4,1,2,9,38,121.0,5,20,1,8,0,0,0,0,0,0,0
1,Chase Edmonds,ARI,0,0,0,0,0,0,0,0,NaN,12,63,0,16,4,4,43,0,36,0,0
2,James Conner,ARI,0,0,0,0,0,0,0,0,NaN,16,53,0,8,0,0,0,0,0,0,0
3,DeAndre Hopkins,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,6,83,2,38,0,0
4,Christian Kirk,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,5,70,2,26,0,0
5,Rondale Moore,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,68,0,29,0,0
6,A.J. Green,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,2,25,0,21,0,0
7,Maxx Williams,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
8,Demetrius Harris,ARI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,0,0,0,0,0,0
11,Ryan Tannehill,TEN,21,35,212,1,1,6,56,39,74.9,2,17,1,16,0,0,0,0,0,2,2
12,Matthias Farley,TEN,1,1,6,0,0,0,0,6,91.7,0,0,0,0,0,0,0,0,0,0,0
13,Derrick Henry,TEN,0,0,0,0,0,0,0,0,NaN,17,58,0,19,4,3,19,0,8,0,0
14,Jeremy McNichols,TEN,0,0,0,0,0,0,0,0,NaN,2,9,0,8,4,3,24,0,9,0,0
15,Mekhi Sargent,TEN,0,0,0,0,0,0,0,0,NaN,1,2,0,2,0,0,0,0,0,0,0
16,Chester Rogers,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,4,62,0,39,0,0
17,A.J. Brown,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,4,49,1,19,0,0
18,Julio Jones,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,3,29,0,10,0,0
19,Anthony Firkser,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,3,19,0,11,0,0
20,Nick Westbrook-Ikhine,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,10,0,10,0,0
21,Amani Hooker,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,6,0,6,0,0
22,Geoff Swaim,TEN,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [30]:
#Sunday Games
URL_13 = 'https://www.pro-football-reference.com/boxscores/202109120ram.htm#player_offense'
table_13 = pd.read_html(URL_13, match = 'Passing, Rushing, & Receiving')
df13 = pd.DataFrame(data=table_13[0])
df13

   Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
               Player                 Tm      Cmp      Att      Yds       TD
0         Andy Dalton                CHI       27       38      206        0
1       Justin Fields                CHI        2        2       10        0
2    David Montgomery                CHI        0        0        0        0
3     Damien Williams                CHI        0        0        0        0
4           Cole Kmet                CHI        0        0        0        0
5      Allen Robinson                CHI        0        0        0        0
6      Darnell Mooney                CHI        0        0        0        0
7        Damiere Byrd                CHI        0        0        0        0
8        Jimmy Graham                CHI        0        0        0        0
9    Marquise Goodwin                CHI        0        0        0        0
10                NaN                NaN  Passing  Passing  Passing  Passing
11             Player                 Tm      Cmp      Att      Yds       TD
12   Matthew Stafford                LAR       20       26      321        3
13  Darrell Henderson                LAR        0        0        0        0
14       Robert Woods                LAR        0        0        0        0
15        Sony Michel                LAR        0        0        0        0
16        Cooper Kupp                LAR        0        0        0        0
17      Van Jefferson                LAR        0        0        0        0
18       Tyler Higbee                LAR        0        0        0        0
19     DeSean Jackson                LAR        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         1        3       28       19     72.9        2       13        0
1         0        0        0        9     87.5        1        3        1
2         0        0        0        0      NaN       16      108        1
3         0        0        0        0      NaN        6       12        0
4         0        0        0        0      NaN        0        0        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        1       -2        0
10  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
11      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
12        0        1        9       67    156.1        5       -5        0
13        0        0        0        0      NaN       16       70        1
14        0        0        0        0      NaN        1        7        0
15        0        0        0        0      NaN        1        2        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         9          0          0          0          0          0        1
1         3          0          0          0          0          0        0
2        41          1          1         10          0         10        0
3         6          5          4         28          0         11        0
4         0          7          5         42          0         10        0
5         0         11          6         35          0          9        0
6         0          7          5         26          0          9        0
7         0          3          3         19          0         10        0
8         0          2          1         11          0         11        0
9        -2          4          4         45          0         19        0
10  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
11      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
12        1          0          0          0          0          0        0
13       15          1          1         17          0         17        0
14        7          4          3         27          1         19        0
15        2          0          0          0          0          0        0
16        0         10          7        108          1         56        0
17        0          3          2         80          1         67        0
18        0          6          5         68          0         37        0
19        0          2          2         21          0         18        0


         FL
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10  Fumbles
11       FL
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0

In [31]:
df13 = df13.drop([10,11])
df13.columns = df13.columns.droplevel(0)
df13

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Andy Dalton,CHI,27,38,206,0,1,3,28,19,72.9,2,13,0,9,0,0,0,0,0,1,1
1,Justin Fields,CHI,2,2,10,0,0,0,0,9,87.5,1,3,1,3,0,0,0,0,0,0,0
2,David Montgomery,CHI,0,0,0,0,0,0,0,0,NaN,16,108,1,41,1,1,10,0,10,0,0
3,Damien Williams,CHI,0,0,0,0,0,0,0,0,NaN,6,12,0,6,5,4,28,0,11,0,0
4,Cole Kmet,CHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,42,0,10,0,0
5,Allen Robinson,CHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,11,6,35,0,9,0,0
6,Darnell Mooney,CHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,7,5,26,0,9,0,0
7,Damiere Byrd,CHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,19,0,10,0,0
8,Jimmy Graham,CHI,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,11,0,11,0,0
9,Marquise Goodwin,CHI,0,0,0,0,0,0,0,0,NaN,1,-2,0,-2,4,4,45,0,19,0,0
12,Matthew Stafford,LAR,20,26,321,3,0,1,9,67,156.1,5,-5,0,1,0,0,0,0,0,0,0
13,Darrell Henderson,LAR,0,0,0,0,0,0,0,0,NaN,16,70,1,15,1,1,17,0,17,0,0
14,Robert Woods,LAR,0,0,0,0,0,0,0,0,NaN,1,7,0,7,4,3,27,1,19,0,0
15,Sony Michel,LAR,0,0,0,0,0,0,0,0,NaN,1,2,0,2,0,0,0,0,0,0,0
16,Cooper Kupp,LAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,10,7,108,1,56,0,0
17,Van Jefferson,LAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,80,1,67,0,0
18,Tyler Higbee,LAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,6,5,68,0,37,0,0
19,DeSean Jackson,LAR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,21,0,18,0,0

In [32]:
#Sunday Games
URL_14 = 'https://www.pro-football-reference.com/boxscores/202109120was.htm#player_offense'
table_14 = pd.read_html(URL_14, match = 'Passing, Rushing, & Receiving')
df14 = pd.DataFrame(data=table_14[0])
df14

   Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
               Player                 Tm      Cmp      Att      Yds       TD
0      Justin Herbert                LAC       31       47      337        1
1       Austin Ekeler                LAC        0        0        0        0
2      Larry Rountree                LAC        0        0        0        0
3      Justin Jackson                LAC        0        0        0        0
4         Gabe Nabers                LAC        0        0        0        0
5        Keenan Allen                LAC        0        0        0        0
6       Mike Williams                LAC        0        0        0        0
7          Jared Cook                LAC        0        0        0        0
8        Jalen Guyton                LAC        0        0        0        0
9           K.J. Hill                LAC        0        0        0        0
10        Josh Palmer                LAC        0        0        0        0
11   Stephen Anderson                LAC        0        0        0        0
12      Donald Parham                LAC        0        0        0        0
13                NaN                NaN  Passing  Passing  Passing  Passing
14             Player                 Tm      Cmp      Att      Yds       TD
15    Taylor Heinicke                WAS       11       15      122        1
16   Ryan Fitzpatrick                WAS        3        6       13        0
17     Antonio Gibson                WAS        0        0        0        0
18    Jaret Patterson                WAS        0        0        0        0
19      J.D. McKissic                WAS        0        0        0        0
20     Terry McLaurin                WAS        0        0        0        0
21       Logan Thomas                WAS        0        0        0        0
22           Cam Sims                WAS        0        0        0        0
23     Adam Humphries                WAS        0        0        0        0
24        Dyami Brown                WAS        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         1        2        3       23     85.2        4       -1        0
1         0        0        0        0      NaN       15       57        1
2         0        0        0        0      NaN        8       27        0
3         0        0        0        0      NaN        1        5        0
4         0        0        0        0      NaN        1        2        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        0        0        0
10        0        0        0        0      NaN        0        0        0
11        0        0        0        0      NaN        0        0        0
12        0        0        0        0      NaN        0        0        0
13  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
14      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
15        0        0        0       34    119.3        3       17        0
16        0        1        2        6     56.2        1        2        0
17        0        0        0        0      NaN       20       90        0
18        0        0        0        0      NaN        2        9        0
19        0        0        0        0      NaN        1        8        0
20        0        0        0        0      NaN        0        0        0
21        0        0        0        0      NaN        0        0        0
22        0        0        0        0      NaN        0        0        0
23        0        0        0        0      NaN        0        0        0
24        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0         2          0          0          0          0          0        1
1        14          0          0          0          0          0        0
2        13          0          0          0          0          0        0
3         5          1          1          2          0          2        0
4         2          0          0          0          0          0        0
5         0         13          9        100          0         17        1
6         0         12          8         82          1         20        0
7         0          8          5         56          0         23        0
8         0          5          3         49          0         22        0
9         0          3          3         30          0         19        0
10        0          1          1         17          0         17        0
11        0          2          1          1          0          1        0
12        0          1          0          0          0          0        0
13  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
14      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
15        9          0          0          0          0          0        0
16        2          0          0          0          0          0        1
17       27          5          3         18          0         11        2
18        5          1          0          0          0          0        0
19        8          1          0          0          0          0        0
20        0          4          4         62          0         34        0
21        0          3          3         30          1         12        0
22        0          1          1         17          0         17        0
23        0          2          2         10          0          6        0
24        0          4          1         -2          0         -2        0


         FL
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13  Fumbles
14       FL
15        0
16        0
17        1
18        0
19        0
20        0
21        0
22        0
23        0
24        0

In [33]:
df14 = df14.drop([13,14])
df14.columns = df14.columns.droplevel(0)
df14

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Justin Herbert,LAC,31,47,337,1,1,2,3,23,85.2,4,-1,0,2,0,0,0,0,0,1,1
1,Austin Ekeler,LAC,0,0,0,0,0,0,0,0,NaN,15,57,1,14,0,0,0,0,0,0,0
2,Larry Rountree,LAC,0,0,0,0,0,0,0,0,NaN,8,27,0,13,0,0,0,0,0,0,0
3,Justin Jackson,LAC,0,0,0,0,0,0,0,0,NaN,1,5,0,5,1,1,2,0,2,0,0
4,Gabe Nabers,LAC,0,0,0,0,0,0,0,0,NaN,1,2,0,2,0,0,0,0,0,0,0
5,Keenan Allen,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,13,9,100,0,17,1,0
6,Mike Williams,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,12,8,82,1,20,0,0
7,Jared Cook,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,5,56,0,23,0,0
8,Jalen Guyton,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,3,49,0,22,0,0
9,K.J. Hill,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,30,0,19,0,0
10,Josh Palmer,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,17,0,17,0,0
11,Stephen Anderson,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,1,0,1,0,0
12,Donald Parham,LAC,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
15,Taylor Heinicke,WAS,11,15,122,1,0,0,0,34,119.3,3,17,0,9,0,0,0,0,0,0,0
16,Ryan Fitzpatrick,WAS,3,6,13,0,0,1,2,6,56.2,1,2,0,2,0,0,0,0,0,1,0
17,Antonio Gibson,WAS,0,0,0,0,0,0,0,0,NaN,20,90,0,27,5,3,18,0,11,2,1
18,Jaret Patterson,WAS,0,0,0,0,0,0,0,0,NaN,2,9,0,5,1,0,0,0,0,0,0
19,J.D. McKissic,WAS,0,0,0,0,0,0,0,0,NaN,1,8,0,8,1,0,0,0,0,0,0
20,Terry McLaurin,WAS,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,62,0,34,0,0
21,Logan Thomas,WAS,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,3,30,1,12,0,0
22,Cam Sims,WAS,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,17,0,17,0,0
23,Adam Humphries,WAS,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,10,0,6,0,0
24,Dyami Brown,WAS,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,1,-2,0,-2,0,0

In [34]:
#Sunday Games
URL_15 = 'https://www.pro-football-reference.com/boxscores/202109130rai.htm#player_offense'
table_15 = pd.read_html(URL_15, match = 'Passing, Rushing, & Receiving')
df15 = pd.DataFrame(data=table_15[0])
df15

   Unnamed: 0_level_0 Unnamed: 1_level_0  Passing                             \
               Player                 Tm      Cmp      Att      Yds       TD
0       Lamar Jackson                BAL       19       30      235        1
1     Ty'Son Williams                BAL        0        0        0        0
2     Latavius Murray                BAL        0        0        0        0
3      Marquise Brown                BAL        0        0        0        0
4      Trenton Cannon                BAL        0        0        0        0
5       Sammy Watkins                BAL        0        0        0        0
6        Mark Andrews                BAL        0        0        0        0
7      Patrick Ricard                BAL        0        0        0        0
8      Devin Duvernay                BAL        0        0        0        0
9         Josh Oliver                BAL        0        0        0        0
10                NaN                NaN  Passing  Passing  Passing  Passing
11             Player                 Tm      Cmp      Att      Yds       TD
12         Derek Carr                LVR       34       56      435        2
13        Josh Jacobs                LVR        0        0        0        0
14     Marcus Mariota                LVR        0        0        0        0
15       Kenyan Drake                LVR        0        0        0        0
16      Darren Waller                LVR        0        0        0        0
17      Bryan Edwards                LVR        0        0        0        0
18     Hunter Renfrow                LVR        0        0        0        0
19          Zay Jones                LVR        0        0        0        0
20    Henry Ruggs III                LVR        0        0        0        0
21        Alec Ingold                LVR        0        0        0        0
22       Willie Snead                LVR        0        0        0        0

                                                 Rushing                    \
        Int       Sk    Yds.1      Lng     Rate      Att      Yds       TD
0         0        3       18       49     98.6       12       86        0
1         0        0        0        0      NaN        9       65        1
2         0        0        0        0      NaN       10       28        1
3         0        0        0        0      NaN        1        5        0
4         0        0        0        0      NaN        2        5        0
5         0        0        0        0      NaN        0        0        0
6         0        0        0        0      NaN        0        0        0
7         0        0        0        0      NaN        0        0        0
8         0        0        0        0      NaN        0        0        0
9         0        0        0        0      NaN        0        0        0
10  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing
11      Int       Sk      Yds      Lng     Rate      Att      Yds       TD
12        1        3       26       37     89.5        4        6        0
13        0        0        0        0      NaN       10       34        2
14        0        0        0        0      NaN        1       31        0
15        0        0        0        0      NaN        6       11        0
16        0        0        0        0      NaN        0        0        0
17        0        0        0        0      NaN        0        0        0
18        0        0        0        0      NaN        0        0        0
19        0        0        0        0      NaN        0        0        0
20        0        0        0        0      NaN        0        0        0
21        0        0        0        0      NaN        0        0        0
22        0        0        0        0      NaN        0        0        0

             Receiving                                              Fumbles  \
        Lng        Tgt        Rec        Yds         TD        Lng      Fmb
0        28          0          0          0          0          0        3
1        35          4          3         29          0         21        0
2         8          0          0          0          0          0        0
3         5          6          6         69          1         29        0
4         3          0          0          0          0          0        0
5         0          8          4         96          0         49        0
6         0          5          3         20          0         10        0
7         0          3          2         15          0          9        0
8         0          2          1          6          0          6        1
9         0          1          0          0          0          0        0
10  Rushing  Receiving  Receiving  Receiving  Receiving  Receiving  Fumbles
11      Lng        Tgt        Rec        Yds         TD        Lng      Fmb
12        4          0          0          0          0          0        1
13       15          2          1          6          0          6        0
14       31          0          0          0          0          0        0
15        6          5          5         59          0         21        0
16        0         19         10        105          1         24        0
17        0          5          4         81          0         32        0
18        0          9          6         70          0         27        0
19        0          2          2         46          1         31        0
20        0          5          2         46          0         37        0
21        0          4          4         22          0          9        0
22        0          1          0          0          0          0        0


         FL
0         2
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10  Fumbles
11       FL
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0

In [35]:
df15 = df15.drop([10,11])
df15.columns = df15.columns.droplevel(0)
df15

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Lamar Jackson,BAL,19,30,235,1,0,3,18,49,98.6,12,86,0,28,0,0,0,0,0,3,2
1,Ty'Son Williams,BAL,0,0,0,0,0,0,0,0,NaN,9,65,1,35,4,3,29,0,21,0,0
2,Latavius Murray,BAL,0,0,0,0,0,0,0,0,NaN,10,28,1,8,0,0,0,0,0,0,0
3,Marquise Brown,BAL,0,0,0,0,0,0,0,0,NaN,1,5,0,5,6,6,69,1,29,0,0
4,Trenton Cannon,BAL,0,0,0,0,0,0,0,0,NaN,2,5,0,3,0,0,0,0,0,0,0
5,Sammy Watkins,BAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,8,4,96,0,49,0,0
6,Mark Andrews,BAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,3,20,0,10,0,0
7,Patrick Ricard,BAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,3,2,15,0,9,0,0
8,Devin Duvernay,BAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,1,6,0,6,1,0
9,Josh Oliver,BAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
12,Derek Carr,LVR,34,56,435,2,1,3,26,37,89.5,4,6,0,4,0,0,0,0,0,1,0
13,Josh Jacobs,LVR,0,0,0,0,0,0,0,0,NaN,10,34,2,15,2,1,6,0,6,0,0
14,Marcus Mariota,LVR,0,0,0,0,0,0,0,0,NaN,1,31,0,31,0,0,0,0,0,0,0
15,Kenyan Drake,LVR,0,0,0,0,0,0,0,0,NaN,6,11,0,6,5,5,59,0,21,0,0
16,Darren Waller,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,19,10,105,1,24,0,0
17,Bryan Edwards,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,4,81,0,32,0,0
18,Hunter Renfrow,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,6,70,0,27,0,0
19,Zay Jones,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,46,1,31,0,0
20,Henry Ruggs III,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,2,46,0,37,0,0
21,Alec Ingold,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,22,0,9,0,0
22,Willie Snead,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [44]:
# Merge all game stats
games=[df,df1,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15]
all_games = pd.concat(games, ignore_index=True, sort=False)
all_games

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0
1,Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,NaN,11,33,0,13,2,2,6,0,3,0,0
2,Tony Pollard,DAL,0,0,0,0,0,0,0,0,NaN,3,14,0,11,4,4,29,0,11,0,0
3,Amari Cooper,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,16,13,139,2,28,0,0
4,CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,15,7,104,1,31,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Hunter Renfrow,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,9,6,70,0,27,0,0
332,Zay Jones,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,2,2,46,1,31,0,0
333,Henry Ruggs III,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,5,2,46,0,37,0,0
334,Alec Ingold,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,4,4,22,0,9,0,0
335,Willie Snead,LVR,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [45]:
all_games['Week'] = 'WK1'
all_games.head()

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL,Week
0,Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0,WK1
1,Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,NaN,11,33,0,13,2,2,6,0,3,0,0,WK1
2,Tony Pollard,DAL,0,0,0,0,0,0,0,0,NaN,3,14,0,11,4,4,29,0,11,0,0,WK1
3,Amari Cooper,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,16,13,139,2,28,0,0,WK1
4,CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,15,7,104,1,31,0,0,WK1

In [46]:
all_games = all_games.set_index('Player')
all_games.head()

,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL,Week
Player,,,,,,,,,,,,,,,,,,,,,,
Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0,WK1
Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,NaN,11,33,0,13,2,2,6,0,3,0,0,WK1
Tony Pollard,DAL,0,0,0,0,0,0,0,0,NaN,3,14,0,11,4,4,29,0,11,0,0,WK1
Amari Cooper,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,16,13,139,2,28,0,0,WK1
CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,15,7,104,1,31,0,0,WK1

In [47]:
all_games.columns

Index(['Tm', 'Cmp', 'Att', 'Yds', 'TD', 'Int', 'Sk', 'Yds.1', 'Lng', 'Rate',
       'Att', 'Yds', 'TD', 'Lng', 'Tgt', 'Rec', 'Yds', 'TD', 'Lng', 'Fmb',
       'FL', 'Week'],
      dtype='object')

In [48]:
all_games = all_games.rename(columns={"Yds.1": "Yds"})
all_games.head()

,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds,Lng,Rate,Att,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL,Week
Player,,,,,,,,,,,,,,,,,,,,,,
Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0,WK1
Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,NaN,11,33,0,13,2,2,6,0,3,0,0,WK1
Tony Pollard,DAL,0,0,0,0,0,0,0,0,NaN,3,14,0,11,4,4,29,0,11,0,0,WK1
Amari Cooper,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,16,13,139,2,28,0,0,WK1
CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,NaN,0,0,0,0,15,7,104,1,31,0,0,WK1

In [49]:
cols=pd.Series(all_games.columns)
for dup in all_games.columns[all_games.columns.duplicated(keep=False)]: 
    cols[all_games.columns.get_loc(dup)] = ([dup + '.' + str(d_idx) 
                                     if d_idx != 0 
                                     else dup 
                                     for d_idx in range(all_games.columns.get_loc(dup).sum())]
                                    )
all_games.columns=cols

In [50]:
all_games = all_games.fillna(0)
all_games.head()

,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Lng,Rate,Att.1,Yds.2,TD.1,Lng.1,Tgt,Rec,Yds.3,TD.2,Lng.2,Fmb,FL,Week
Player,,,,,,,,,,,,,,,,,,,,,,
Dak Prescott,DAL,42,58,403,3,1,1,12,31,101.4,4,13,0,7,0,0,0,0,0,1,0,WK1
Ezekiel Elliott,DAL,0,0,0,0,0,0,0,0,0,11,33,0,13,2,2,6,0,3,0,0,WK1
Tony Pollard,DAL,0,0,0,0,0,0,0,0,0,3,14,0,11,4,4,29,0,11,0,0,WK1
Amari Cooper,DAL,0,0,0,0,0,0,0,0,0,0,0,0,0,16,13,139,2,28,0,0,WK1
CeeDee Lamb,DAL,0,0,0,0,0,0,0,0,0,0,0,0,0,15,7,104,1,31,0,0,WK1

In [51]:
# Saving as a csv 
all_games.to_csv('Resources/Week_1.csv')